#pragma once

/* Upstream miniz expects miniz_export.h generated by its CMake build (shared-library
   visibility). The vendored TU set compiles statically, so both macros stay empty. */
#define MINIZ_EXPORT
#define MINIZ_NO_EXPORT
