/*
 * MetaScript System Header — Master Include
 * This is the single header that generated C code includes.
 * It pulls in ARC, String, and Array runtimes.
 */
#ifndef SYSTEM_H
#define SYSTEM_H

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* ARC foundation (refcount, alloc, typeinfo) */
#include "mem/arc.h"

/* ORC cycle collector (behind MS_ORC flag; no-op stubs otherwise) */
#include "mem/orc.h"

/* String runtime (msString, all string ops) */
#include "core/string.h"

/* Array runtime (msNumberArray, msStringArray, msRefArray) */
#include "core/array.h"

/* Map runtime (msMap — string-keyed hash map) */
#include "core/map.h"

/* ===== Type Aliases (C89 portability + codegen convenience) ===== */
typedef bool MS_BOOL;
#define MS_TRUE true
#define MS_FALSE false
#define MS_NIL NULL

/* ===== I/O ===== */

void msPrintln(msString s);

/* ===== DRC Lifecycle Stubs ===== */

/* Global error flag (exception handling) */
extern bool msErr;

/* Closure function pointer types — with env (for lifted closures) */
typedef void (*msClosureFn)(void*, ...);
typedef double (*msClosureFnD)(void*, ...);
typedef MS_BOOL (*msClosureFnB)(void*, ...);
typedef msString (*msClosureFnS)(void*, ...);
typedef int32_t (*msClosureFnI)(void*, ...);
typedef int64_t (*msClosureFnI64)(void*, ...);
typedef void* (*msClosureFnP)(void*, ...);
/* Direct function pointer casts for named functions wrapped as closures:
   Standard reference pattern — per-call-site typed casts generated by closureCallLower.
   No generic typedefs needed; each call site gets its own typed cast like:
     ((MS_BOOL(*)(double))(pred.fn))(args)
   This avoids -Wdeprecated-non-prototype warnings from empty-paren typedefs. */
typedef struct {
	msClosureFn fn;
	void* env;
} msClosure;

/* Exception handling */
typedef struct {
	const char* message;
	int code;
} msException;

extern MS_BOOL msErr;
extern msException* msCurrException;
void msClearException(void);
void msThrow(msString msg);

/* ===== DRC Lifecycle Macros ===== */
/* DRC passes args by value — macros access the variable directly for mutation. */

/* --- String lifecycle --- */
#define msStringDecref(s)     msStringDestroy(s)
#define msStringIncref(s)     do { \
	if ((s).p != NULL && !msIsLiteral(s)) { \
		msString __c = msStringNew((s).p->data, (s).len); \
		(s) = __c; \
	} \
} while(0)
#define msStringWasMoved(s)   do { (s).len = 0; (s).p = NULL; } while(0)
#define msStringSink(d, s)    do { msStringDestroy(d); (d) = (s); } while(0)

/* --- Array lifecycle (unified) --- */
/* Payload-only free — inline loops handle per-element cleanup (Reference parity: sequence op) */
#define msArrayDestroy(arr)            do { if ((arr).p) { free((arr).p); (arr).p = NULL; } (arr).len = 0; } while(0)
#define msArrayWasMoved(arr)           do { (arr).len = 0; (arr).p = NULL; } while(0)
#define msArrayCopy(arr)               /* primitive: bitwise copy handled by assignment */
#define msArraySetLen(d, s)            msArraySetLenGeneric(&(d), (s).len, sizeof((s).p->data[0]))

/* --- Legacy aliases (used by classify.ms for DRC injection layer) --- */
#define msArrayNumberWasMoved(arr)     msArrayWasMoved(arr)
#define msArrayNumberSink(d, s)        do { msArrayDestroy(d); (d) = (s); } while(0)
#define msArrayStringDestroy(arr)      msStringArrayDestroy(&(arr))
#define msArrayStringCopy(d, s)        do { \
	msStringArrayDestroy(&(d)); \
	(d).len = (s).len; \
	if ((s).p) { \
		size_t _asc_sz = sizeof(msStringPayload) + (size_t)(s).p->cap * sizeof(msString); \
		(d).p = (msStringPayload*)malloc(_asc_sz); \
		(d).p->cap = (s).p->cap; \
		for (int64_t _asc_i = 0; _asc_i < (s).len; _asc_i++) { \
			(d).p->data[_asc_i] = (s).p->data[_asc_i]; \
			msStringIncref((d).p->data[_asc_i]); \
		} \
	} else { (d).p = NULL; } \
} while(0)
#define msArrayStringWasMoved(arr)     msArrayWasMoved(arr)
#define msArrayStringSink(d, s)        do { msArrayDestroy(d); (d) = (s); } while(0)
#define msArrayRefDestroy(arr)         msRefArrayDestroy(&(arr))
#define msArrayRefCopy(d, s)           do { \
	msRefArrayDestroy(&(d)); \
	(d).len = (s).len; \
	if ((s).p) { \
		size_t _arc_sz = sizeof(msRefPayload) + (size_t)(s).p->cap * sizeof(void*); \
		(d).p = (msRefPayload*)malloc(_arc_sz); \
		(d).p->cap = (s).p->cap; \
		for (int64_t _arc_i = 0; _arc_i < (s).len; _arc_i++) { \
			(d).p->data[_arc_i] = (s).p->data[_arc_i]; \
			if ((d).p->data[_arc_i]) msIncRef((d).p->data[_arc_i]); \
		} \
	} else { (d).p = NULL; } \
} while(0)
#define msArrayRefTrace(arr, cb)       do { \
	for (int64_t _art_i = 0; _art_i < (arr).len && (arr).p; _art_i++) { \
		if ((arr).p->data[_art_i]) ((void(*)(void*))(cb))((arr).p->data[_art_i]); \
	} \
} while(0)
#define msArrayRefWasMoved(arr)        msArrayWasMoved(arr)
#define msArrayUint8Destroy(arr)       msUint8ArrayDestroy(&(arr))
#define msArrayUint8WasMoved(arr)      msArrayWasMoved(arr)
#define msArrayUint8Sink(d, s)         do { msArrayDestroy(d); (d) = (s); } while(0)

/* --- Ref/Ptr lifecycle (generic heap objects) --- */
#define msIncref(p)           msIncRef(p)
#define msDecref(p)           do { \
	if ((p) != NULL && msDecRefIsLast(p)) { \
		const msTypeInfo* __t = msHeader(p)->type; \
		if (__t != NULL && __t->destroyFn != NULL) __t->destroyFn(p); \
		msDestroyAndDispose(p); \
	} \
} while(0)
#define msPtrWasMoved(p)      msWasMoved(p)

/* --- ORC-aware ref lifecycle for cyclic types (Standard reference implementation parity) --- */
#ifdef MS_ORC
#define msIncrefCyclic(p)     do { if ((p) != NULL) msOrcIncRef(p); } while(0)
#define msDecrefCyclic(p)     do { \
	if ((p) != NULL && msOrcDecRefIsLast(p)) { \
		const msTypeInfo* __t = msHeader(p)->type; \
		if (__t != NULL && __t->destroyFn != NULL) __t->destroyFn(p); \
		msDestroyAndDispose(p); \
	} \
} while(0)
#else
#define msIncrefCyclic(p)     msIncref(p)
#define msDecrefCyclic(p)     msDecref(p)
#endif

/* --- Closure lifecycle --- */
#define msClosureDestroy(c)   do { if ((c).env != NULL) { msDecref((c).env); } (c).fn = NULL; (c).env = NULL; } while(0)
#define msClosureCopy(c)      do { if ((c).env != NULL) msIncRef((c).env); } while(0)
#define msClosureWasMoved(c)  do { (c).fn = NULL; (c).env = NULL; } while(0)
#define msClosureSink(d, s)   do { msClosureDestroy(d); (d) = (s); } while(0)
#define msClosureTrace(c, _env) do { if ((c).env != NULL) msOrcTraceRef((c).env, (_env)); } while(0)

/* --- Map lifecycle --- */
/* DRC emits these as fn(varName) — macros handle address-of */
#define msMapFree(m)          msMapDestroy(&(m))
#define msMapCopy(m)          do { msMap __mc = msMapCopyFn(m); (m) = __mc; } while(0)
#define msMapWasMoved(m)      do { (m).len = 0; (m).p = NULL; } while(0)
#define msMapSink(d, s)       do { msMapDestroy(&(d)); (d) = (s); } while(0)
#define msMapTrace(m)         /* TODO: ORC trace */

/* --- Set = Map with NULL values --- */
typedef msMap msSet;
#define msSetNew()            msMapNew(NULL)
#define msSetFree(s)          msMapFree(s)
#define msSetCopy(s)          msMapCopy(s)
#define msSetWasMoved(s)      msMapWasMoved(s)
#define msSetSink(d, s)       msMapSink(d, s)
#define msSetTrace(s)         msMapTrace(s)

/* --- Named object wasMoved (no-op for value-type named objects) --- */
#define msObjectWasMoved(p)   /* no-op */

/* ===== Error Reporting ===== */

/* Bounds check failure — prints error and exits */
_Noreturn void msRaiseIndexError(int64_t idx, int64_t len);

/* ===== Bounds-Checked Array Access Macros ===== */
/* GCC statement expressions returning lvalues via dereferenced-pointer trick.
   Both reads (x = msNumberArrayAccess(a, i)) and writes (msNumberArrayAccess(a, i) = x) work. */

#define msNumberArrayAccess(a, i) (*({ \
	int32_t __idx = (i); \
	if ((uint32_t)__idx >= (uint32_t)(a).len) msRaiseIndexError(__idx, (a).len); \
	&((a).p->data[__idx]); \
}))

#define msStringArrayAccess(a, i) (*({ \
	int32_t __idx = (i); \
	if ((uint32_t)__idx >= (uint32_t)(a).len) msRaiseIndexError(__idx, (a).len); \
	&((a).p->data[__idx]); \
}))

#define msRefArrayAccess(a, i) (*({ \
	int32_t __idx = (i); \
	if ((uint32_t)__idx >= (uint32_t)(a).len) msRaiseIndexError(__idx, (a).len); \
	&((a).p->data[__idx]); \
}))

#define msUint8ArrayAccess(a, i) (*({ \
	int32_t __idx = (i); \
	if ((uint32_t)__idx >= (uint32_t)(a).len) msRaiseIndexError(__idx, (a).len); \
	&((a).p->data[__idx]); \
}))

#define msSizedArrayAccess(a, i, n) (*({ \
	int32_t __idx = (i); \
	if ((uint32_t)__idx >= (uint32_t)(n)) msRaiseIndexError(__idx, (n)); \
	&((a).data[__idx]); \
}))

#define msSpanAccess(a, i) (*({ \
	int32_t __idx = (i); \
	if ((uint32_t)__idx >= (uint32_t)(a).len) msRaiseIndexError(__idx, (a).len); \
	&((a).data[__idx]); \
}))

/* String char access is read-only — no lvalue trick needed */
#define msStringCharAccess(s, i) ({ \
	int32_t __idx = (i); \
	if ((uint32_t)__idx >= (uint32_t)(s).len) msRaiseIndexError(__idx, (s).len); \
	msStringCharAt((s), __idx); \
})

#endif /* SYSTEM_H */
