/*
 * MetaScript Actor Runtime
 *
 * Actor = state struct + MPSC mailbox + dispatch function.
 * Scheduler polls actor mailboxes directly (no syscall, no pipe).
 * Scheduler 0 also runs msRunOnce() for I/O + timers + spawn.
 *
 * Lifecycle: msActorCreate → msActorSend/msActorCall → msActorProcess → msActorDestroy
 */

#ifndef MS_ACTOR_H
#define MS_ACTOR_H

#include "mailbox.h"
#include "runtime/drc.h"
#include <stdint.h>
#include <stdbool.h>

/* ===== Actor Dispatch Function ===== */

/* Dispatch receives state + full message (void* → msMessage*).
 * Dispatch accesses msg->kind for routing and msg->replyFuture for call-semantics. */
typedef void (*msActorDispatchFn)(void* state, void* msg);

/* ===== Sync Flags (Pony-derived) ===== */

#define MS_ACTOR_OVERLOADED     0x01  /* mailbox non-empty after batch */
#define MS_ACTOR_UNDER_PRESSURE 0x02  /* application-level backpressure */
#define MS_ACTOR_MUTED          0x04  /* paused by scheduler (target overloaded) */
#define MS_ACTOR_BLOCKED        0x08  /* idle + RC > 0 (cycle detection candidate) */
#define MS_ACTOR_CYCLE_MARKED   0x10  /* internal: marked for cycle collection (do not reuse MUTED) */

/* ===== Actor Struct ===== */

typedef struct msActor {
    msMpscQueue mailbox;          /* Lock-free MPSC message queue */
    msActorDispatchFn dispatch;   /* Message handler (generated by compiler) */
    void* state;                  /* Pointer to actor's data struct (Ref<T>) */
    int32_t schedulerID;          /* Pinned scheduler index */
    _Atomic(uint8_t) syncFlags;   /* Backpressure + lifecycle flags */
    _Atomic(bool) hasWork;        /* Set on push, cleared after drain */
    _Atomic(bool) processing;     /* CAS guard: only one thread may process at a time (enables work stealing) */
    _Atomic(struct msActor*) runNext;  /* Intrusive run queue link (lock-free stack per scheduler) */
    /* Muting: actors paused because this actor is overloaded (dynamic, malloc on first use) */
    struct msActor** mutedBy;
    int mutedByCount;
    int mutedByCap;
    /* Cycle detection: actors this actor references (dynamic, malloc on first use) */
    struct msActor** refs;
    int refsCount;
    int refsCap;
} msActor;

/* ===== Batch Size ===== */

#define MS_ACTOR_BATCH 64
#define MS_CYCLE_INTERVAL 100  /* run cycle detector every N polls */

/* ===== Thread-local: currently executing actor (NULL if non-actor code) ===== */

#ifndef MS_THREAD_LOCAL
#ifdef _WIN32
#define MS_THREAD_LOCAL __declspec(thread)
#else
#define MS_THREAD_LOCAL _Thread_local
#endif
#endif

static MS_THREAD_LOCAL msActor* msCurrentActor = NULL;

/* ===== Flag Helpers ===== */

static inline uint8_t msActorGetFlags(msActor* a) {
    return atomic_load_explicit(&a->syncFlags, memory_order_acquire);
}

static inline void msActorSetFlag(msActor* a, uint8_t flag) {
    atomic_fetch_or_explicit(&a->syncFlags, flag, memory_order_release);
}

static inline void msActorClearFlag(msActor* a, uint8_t flag) {
    atomic_fetch_and_explicit(&a->syncFlags, (uint8_t)~flag, memory_order_release);
}

static inline bool msActorHasFlag(msActor* a, uint8_t flag) {
    return (msActorGetFlags(a) & flag) != 0;
}

/* ===== Muting ===== */

/* Mute a sender because the receiver is overloaded. */
static inline void msActorMute(msActor* sender, msActor* receiver) {
    if (sender == NULL || sender == receiver) return;
    if (msActorHasFlag(sender, MS_ACTOR_MUTED)) return;
    msActorSetFlag(sender, MS_ACTOR_MUTED);
    /* Track who we muted so we can unmute them later (grow on demand) */
    if (receiver->mutedByCount >= receiver->mutedByCap) {
        int newCap = receiver->mutedByCap == 0 ? 4 : receiver->mutedByCap * 2;
        receiver->mutedBy = (msActor**)realloc(receiver->mutedBy, newCap * sizeof(msActor*));
        receiver->mutedByCap = newCap;
    }
    receiver->mutedBy[receiver->mutedByCount++] = sender;
}

/* Unmute all actors that were muted because this actor was overloaded. */
static inline void msActorUnmuteAll(msActor* receiver) {
    for (int i = 0; i < receiver->mutedByCount; i++) {
        msActorClearFlag(receiver->mutedBy[i], MS_ACTOR_MUTED);
        receiver->mutedBy[i] = NULL;
    }
    receiver->mutedByCount = 0;
}

/* ===== Actor Lifecycle ===== */

static inline msActor* msActorCreate(void* state, msActorDispatchFn dispatch) {
    msActor* a = (msActor*)calloc(1, sizeof(msActor));
    msMpscInit(&a->mailbox);
    a->dispatch = dispatch;
    a->state = state;
    a->schedulerID = 0;
    atomic_store_explicit(&a->syncFlags, 0, memory_order_relaxed);
    atomic_store_explicit(&a->hasWork, false, memory_order_relaxed);
    atomic_store_explicit(&a->processing, false, memory_order_relaxed);
    atomic_store_explicit(&a->runNext, NULL, memory_order_relaxed);
    a->mutedBy = NULL;
    a->mutedByCount = 0;
    a->mutedByCap = 0;
    a->refs = NULL;
    a->refsCount = 0;
    a->refsCap = 0;
    return a;
}

/* ===== Multi-Scheduler (forward declarations needed by msActorSend) ===== */

#define MS_MAX_ACTORS_PER_SCHED 256
#define MS_MAX_SCHEDULERS 64

typedef struct msSchedActors {
    msActor* actors[MS_MAX_ACTORS_PER_SCHED];  /* registry: all actors assigned here */
    _Atomic(int) count;  /* atomic: CD reads while main thread may register */
    int pollCount;  /* for periodic cycle detection (scheduler 0 only) */
    _Atomic(msActor*) runHead;  /* lock-free run queue: actors with pending messages */
} msSchedActors;

static msSchedActors msSchedulers[MS_MAX_SCHEDULERS];
static int msSchedulerCount = 0;

/* Push actor onto scheduler's run queue (any thread, lock-free). O(1). */
static inline void msSchedRunPush(msSchedActors* sched, msActor* a) {
    msActor* head = atomic_load_explicit(&sched->runHead, memory_order_relaxed);
    do {
        atomic_store_explicit(&a->runNext, head, memory_order_relaxed);
    } while (!atomic_compare_exchange_weak_explicit(&sched->runHead, &head, a,
        memory_order_release, memory_order_relaxed));
}

/* Pop one actor from scheduler's run queue (any thread, lock-free CAS). O(1). */
static inline msActor* msSchedRunPop(msSchedActors* sched) {
    msActor* head = atomic_load_explicit(&sched->runHead, memory_order_acquire);
    while (head != NULL) {
        msActor* next = atomic_load_explicit(&head->runNext, memory_order_relaxed);
        if (atomic_compare_exchange_weak_explicit(&sched->runHead, &head, next,
                memory_order_acq_rel, memory_order_acquire)) {
            atomic_store_explicit(&head->runNext, NULL, memory_order_relaxed);
            return head;
        }
    }
    return NULL;
}

/* Forward declarations for wake routing */
extern void msActorWakeEventLoop(void);  /* dispatch.c */
extern void msPoolWakeWorker(int schedulerID);  /* pool.c — targeted, no spurious wakeups */

/* Forward declarations for cycle detector (defined at end of file) */
static inline void msCDInit(void);
static inline void msCDTick(void);

/*
 * Send a message to an actor (any thread, wait-free).
 * If receiver is overloaded, mutes the current actor (sender).
 */
static inline void msActorSend(msActor* a, msMessage* msg) {
    bool wasEmpty = msMpscPush(&a->mailbox, msg);
    atomic_store_explicit(&a->hasWork, true, memory_order_release);

    /* Backpressure: if receiver overloaded, mute sender */
    if (msActorHasFlag(a, MS_ACTOR_OVERLOADED) && msCurrentActor != NULL) {
        msActorMute(msCurrentActor, a);
    }

    if (wasEmpty) {
        /* Enqueue actor into scheduler's run queue — O(1) lock-free push.
         * Schedulers pop from this queue instead of scanning all actors. */
        if (a->schedulerID >= 0 && a->schedulerID < msSchedulerCount) {
            msSchedRunPush(&msSchedulers[a->schedulerID], a);
        }
        /* Wake the target scheduler thread */
        if (a->schedulerID == 0) {
            msActorWakeEventLoop();
        } else {
            msPoolWakeWorker(a->schedulerID);
        }
    }
}

/*
 * Process up to `maxBatch` messages from the actor's mailbox.
 * Sets/clears OVERLOADED flag. Triggers unmute when caught up.
 */
static inline int msActorProcess(msActor* a, int maxBatch) {
    /* CAS guard: only one thread may process this actor at a time.
     * Enables work stealing — any idle thread can safely call this. */
    bool expected = false;
    if (!atomic_compare_exchange_strong_explicit(&a->processing, &expected, true,
            memory_order_acquire, memory_order_relaxed)) {
        return 0;  /* another thread is already processing this actor */
    }

    msActor* prevActor = msCurrentActor;
    msCurrentActor = a;

    /* Clear BLOCKED — we're actively processing */
    msActorClearFlag(a, MS_ACTOR_BLOCKED);

    int processed = 0;
    while (processed < maxBatch) {
        msMessage* msg = msMpscPop(&a->mailbox);
        if (msg == NULL) break;
        a->dispatch(a->state, (void*)msg);
        /* Don't free msg here — MPSC pop made it the new tail stub.
         * It gets freed on the NEXT pop when a newer message takes its place. */
        processed++;
    }

    /* Check mailbox state after batch */
    if (msMpscIsEmpty(&a->mailbox)) {
        if (msMpscMarkEmpty(&a->mailbox)) {
            atomic_store_explicit(&a->hasWork, false, memory_order_release);
        }
        /* Caught up: clear overload + unmute senders */
        if (msActorHasFlag(a, MS_ACTOR_OVERLOADED)) {
            msActorClearFlag(a, MS_ACTOR_OVERLOADED);
            msActorUnmuteAll(a);
        }
        /* Idle with RC > 0: candidate for cycle detection */
        if (a->state != NULL) {
            msRefHeader* h = msHeader(a->state);
            if (h->rc > 0) {
                msActorSetFlag(a, MS_ACTOR_BLOCKED);
            }
        }
    } else {
        /* Still has messages after batch: mark overloaded */
        msActorSetFlag(a, MS_ACTOR_OVERLOADED);
    }

    msCurrentActor = prevActor;
    atomic_store_explicit(&a->processing, false, memory_order_release);
    return processed;
}

/* ===== Message Accessors (for dispatch functions generated by compiler) ===== */

static inline int32_t msMsgKind(void* msg) {
    return ((msMessage*)msg)->kind;
}

static inline void* msMsgReplyFuture(void* msg) {
    return ((msMessage*)msg)->replyFuture;
}

/* Future completion helpers — thin wrappers so dispatch can complete reply futures.
 * These call into future.h APIs. Include future.h before actor.h for call-semantics. */
static inline void msMsgCompleteDouble(void* fut, double val) {
    if (fut == NULL) return;
    /* Cast to msFuture_double* and complete. Requires future.h to be included. */
    typedef struct { bool finished; bool failed; bool cancelled; bool isBoxed; void* error; void (*vd)(void*); void* cb; void* cbTail; double value; } msFutSimpleDouble;
    msFutSimpleDouble* f = (msFutSimpleDouble*)fut;
    f->value = val;
    f->finished = true;
}

static inline void msMsgCompleteVoid(void* fut) {
    if (fut == NULL) return;
    typedef struct { bool finished; } msFutSimpleVoid;
    msFutSimpleVoid* f = (msFutSimpleVoid*)fut;
    f->finished = true;
}

static inline void msActorDestroy(msActor* a) {
    /* Unmute anyone we caused to be muted */
    msActorUnmuteAll(a);
    /* Drain remaining messages */
    msMessage* msg;
    while ((msg = msMpscPop(&a->mailbox)) != NULL) {
        msMsgFree(msg);
    }
    msMpscDestroy(&a->mailbox);
    if (a->mutedBy != NULL) free(a->mutedBy);
    if (a->refs != NULL) free(a->refs);
    free(a);
}

/* ===== Actor References (for cycle detection) ===== */

static inline void msActorAddRef(msActor* from, msActor* to) {
    if (from == NULL || to == NULL || from == to) return;
    /* Check for duplicate */
    for (int i = 0; i < from->refsCount; i++) {
        if (from->refs[i] == to) return;
    }
    /* Grow on demand */
    if (from->refsCount >= from->refsCap) {
        int newCap = from->refsCap == 0 ? 4 : from->refsCap * 2;
        from->refs = (msActor**)realloc(from->refs, newCap * sizeof(msActor*));
        from->refsCap = newCap;
    }
    from->refs[from->refsCount++] = to;
}

/* ===== Multi-Scheduler Actor Registry (Phase 5: Parallel Actors) =====
 *
 * Actors are round-robin assigned to schedulers (threads).
 * Scheduler 0 = main thread (also runs msRunOnce for I/O).
 * Schedulers 1..N-1 = spawn pool worker threads.
 * Run queues: lock-free stack per scheduler — O(1) push/pop, scales to 10K+ actors.
 * Work stealing: idle workers pop from other schedulers' run queues — O(schedulers).
 */

static _Atomic(int) msNextActorRR = 0;    /* round-robin assignment counter */

/* Thread-local: which scheduler am I? (-1 = unassigned) */
static MS_THREAD_LOCAL int msMySchedulerID = -1;

/* Forward declarations */
extern void msSetActorPollHook(bool (*hook)(void));  /* dispatch.c */
extern void msPoolSetActorHooks(bool (*pollFn)(void), void (*idSetterFn)(int));  /* pool.c */
static inline bool msActorPollLocal(void);            /* defined below */

#include "runtime/promise/pool.h"

/* Scheduler ID setter — called by pool workers via hook to set their TLS scheduler ID */
static inline void msSetSchedulerID(int id) {
    msMySchedulerID = id;
}

static inline void msActorRegister(msActor* a) {
    if (msSchedulerCount == 0) {
        /* First actor: initialize scheduler infrastructure */
        msThreadPool* p = msPoolGet();
        msSchedulerCount = (p != NULL ? p->workerCount : 0) + 1;
        if (msSchedulerCount > MS_MAX_SCHEDULERS) msSchedulerCount = MS_MAX_SCHEDULERS;
        msMySchedulerID = 0;  /* main thread = scheduler 0 */
        msSetActorPollHook(msActorPollLocal);
        /* Register hooks so pool workers can poll actors + set scheduler ID */
        msPoolSetActorHooks(msActorPollLocal, msSetSchedulerID);
        /* Create async cycle detector actor on scheduler 0 */
        msCDInit();
    }
    /* Round-robin assign to schedulers */
    int id = atomic_fetch_add(&msNextActorRR, 1) % msSchedulerCount;
    a->schedulerID = id;
    msSchedActors* sched = &msSchedulers[id];
    int cnt = atomic_load_explicit(&sched->count, memory_order_acquire);
    if (cnt < MS_MAX_ACTORS_PER_SCHED) {
        sched->actors[cnt] = a;
        atomic_store_explicit(&sched->count, cnt + 1, memory_order_release);
    }
}

/*
 * Poll actors on THIS scheduler thread only.
 * Called from: main thread (via msRunOnce hook) and pool workers (after spawn tasks).
 */
static inline bool msActorPollLocal(void) {
    int id = msMySchedulerID;
    if (id < 0 || id >= msSchedulerCount) return false;
    bool didWork = false;

    /* Phase 1: Drain own run queue — O(1) per actor, only actors with work.
     * Pony parity: pop from queue, not scan array. Scales to 10K+ actors. */
    msSchedActors* sched = &msSchedulers[id];
    msActor* a;
    while ((a = msSchedRunPop(sched)) != NULL) {
        if (msActorHasFlag(a, MS_ACTOR_MUTED)) continue;
        int n = msActorProcess(a, MS_ACTOR_BATCH);
        if (n > 0) didWork = true;
    }

    /* Phase 2: Work stealing — if idle, pop from other schedulers' run queues.
     * O(schedulers) not O(actors). CAS guard prevents double-processing. */
    if (!didWork) {
        for (int s = 0; s < msSchedulerCount; s++) {
            if (s == id) continue;
            msSchedActors* other = &msSchedulers[s];
            a = msSchedRunPop(other);
            if (a != NULL) {
                if (!msActorHasFlag(a, MS_ACTOR_MUTED)) {
                    int n = msActorProcess(a, MS_ACTOR_BATCH);
                    if (n > 0) didWork = true;
                }
                break;  /* stole one actor, return to own work */
            }
        }
    }

    /* Cycle detection: scheduler 0 sends periodic TICK to CD actor (async) */
    if (id == 0) {
        sched->pollCount++;
        if (sched->pollCount >= MS_CYCLE_INTERVAL) {
            sched->pollCount = 0;
            msCDTick();
        }
    }
    return didWork;
}

/* Exit-poll: drain ALL run queues + scan ALL registries (belt-and-suspenders).
 * Called at program exit to flush remaining messages. */
static inline bool msActorPollAll(void) {
    bool didWork = false;
    /* Drain run queues first */
    for (int s = 0; s < msSchedulerCount; s++) {
        msActor* a;
        while ((a = msSchedRunPop(&msSchedulers[s])) != NULL) {
            if (!msActorHasFlag(a, MS_ACTOR_MUTED)) {
                int n = msActorProcess(a, MS_ACTOR_BATCH);
                if (n > 0) didWork = true;
            }
        }
    }
    /* Scan registry for stragglers not in run queue */
    for (int s = 0; s < msSchedulerCount; s++) {
        msSchedActors* sched = &msSchedulers[s];
        for (int i = 0; i < sched->count; i++) {
            msActor* a = sched->actors[i];
            if (msActorHasFlag(a, MS_ACTOR_MUTED)) continue;
            if (atomic_load_explicit(&a->hasWork, memory_order_acquire)) {
                int n = msActorProcess(a, MS_ACTOR_BATCH);
                if (n > 0) didWork = true;
            }
        }
    }
    return didWork;
}

/* Quiescence detection: true when ALL actors across ALL schedulers are idle. */
static inline bool msActorSystemQuiescent(void) {
    for (int s = 0; s < msSchedulerCount; s++) {
        msSchedActors* sched = &msSchedulers[s];
        for (int i = 0; i < sched->count; i++) {
            msActor* a = sched->actors[i];
            if (atomic_load_explicit(&a->hasWork, memory_order_acquire)) return false;
            if (atomic_load_explicit(&a->processing, memory_order_acquire)) return false;
        }
    }
    return true;
}

/* ===== Async Cycle Detector Actor (Pony ORCA parity) =====
 *
 * The CD is a system actor on scheduler 0. It receives periodic TICK messages
 * from msActorPollLocal, scans BLOCKED flags across all schedulers, and
 * detects dead reference cycles. Non-blocking — runs as a normal actor batch.
 *
 * Protocol:
 *   1. msActorProcess sets BLOCKED flag when actor becomes idle (RC > 0)
 *   2. msActorProcess clears BLOCKED flag when actor gets new work
 *   3. msActorPollLocal (scheduler 0) sends TICK to CD every MS_CYCLE_INTERVAL polls
 *   4. CD dispatch scans all schedulers for blocked actors with all-blocked refs
 *   5. Dead cycles → destroy (Phase 6: trigger link/monitor propagation)
 */

#define MS_CD_MSG_TICK 0

/* Scan all schedulers for dead cycles.
 * An actor is in a dead cycle if: BLOCKED + all refs also BLOCKED. */
static inline void msCDRunDetection(void) {
    /* Pass 1: find cycle candidates (blocked + all refs blocked) */
    for (int s = 0; s < msSchedulerCount; s++) {
        msSchedActors* sched = &msSchedulers[s];
        for (int i = 0; i < sched->count; i++) {
            msActor* a = sched->actors[i];
            if (!msActorHasFlag(a, MS_ACTOR_BLOCKED)) continue;
            if (a->refsCount == 0) continue;
            bool allRefsBlocked = true;
            for (int r = 0; r < a->refsCount; r++) {
                if (!msActorHasFlag(a->refs[r], MS_ACTOR_BLOCKED)) {
                    allRefsBlocked = false;
                    break;
                }
            }
            if (allRefsBlocked) {
                msActorSetFlag(a, MS_ACTOR_CYCLE_MARKED);
            }
        }
    }
    /* Pass 2: collect marked actors */
    for (int s = 0; s < msSchedulerCount; s++) {
        msSchedActors* sched = &msSchedulers[s];
        for (int i = sched->count - 1; i >= 0; i--) {
            msActor* a = sched->actors[i];
            if (msActorHasFlag(a, MS_ACTOR_CYCLE_MARKED)) {
                msActorClearFlag(a, MS_ACTOR_CYCLE_MARKED);
                /* Remove from registry */
                sched->actors[i] = sched->actors[sched->count - 1];
                sched->count--;
                msActorDestroy(a);
            }
        }
    }
}

/* CD actor dispatch — receives TICK messages, runs detection */
static inline void msCDDispatch(void* state, void* msg) {
    (void)state; (void)msg;
    msCDRunDetection();
}

/* The global CD actor — created during scheduler init */
static msActor* msCycleDetectorActor = NULL;

static inline void msCDInit(void) {
    if (msCycleDetectorActor != NULL) return;
    msCycleDetectorActor = msActorCreate(NULL, msCDDispatch);
    msCycleDetectorActor->schedulerID = 0;
    msSchedActors* sched = &msSchedulers[0];
    int cnt = atomic_load_explicit(&sched->count, memory_order_acquire);
    if (cnt < MS_MAX_ACTORS_PER_SCHED) {
        sched->actors[cnt] = msCycleDetectorActor;
        atomic_store_explicit(&sched->count, cnt + 1, memory_order_release);
    }
}

/* Send TICK to CD actor (called from msActorPollLocal on scheduler 0) */
static inline void msCDTick(void) {
    if (msCycleDetectorActor == NULL) return;
    msMessage* msg = msMsgAlloc(MS_CD_MSG_TICK, NULL);
    msActorSend(msCycleDetectorActor, msg);
}

#endif /* MS_ACTOR_H */
