/*
 * MetaScript Actor Runtime
 *
 * Actor = state struct + MPSC mailbox + dispatch function.
 * Scheduler polls actor mailboxes directly (no syscall, no pipe).
 * Scheduler 0 also runs msRunOnce() for I/O + timers + spawn.
 *
 * Lifecycle: msActorCreate → msActorSend/msActorCall → msActorProcess → msActorDestroy
 */

#ifndef MS_ACTOR_H
#define MS_ACTOR_H

#include "mailbox.h"
#include "runtime/drc.h"
#include <stdint.h>
#include <stdbool.h>
#include <pthread.h>

/* ===== Actor Dispatch Function ===== */

/* Dispatch receives state + full message (void* → msMessage*).
 * Dispatch accesses msg->kind for routing and msg->replyFuture for call-semantics. */
typedef void (*msActorDispatchFn)(void* state, void* msg);

/* ===== ExitReason (Erlang OTP parity) ===== */

#define MS_EXIT_NORMAL   0  /* clean shutdown */
#define MS_EXIT_KILLED   1  /* forced kill (supervisor restart, system shutdown) */
#define MS_EXIT_ABNORMAL 2  /* crash (unhandled panic/error) */

/* onTerminate callback: called before actor is destroyed. Can send messages, flush. */
typedef void (*msActorOnTerminateFn)(void* state, int32_t reason);

/* System message callback: routes EXIT (kind=-1) and DOWN (kind=-2) to user handlers. */
typedef void (*msActorSystemMsgFn)(void* state, void* msg);

/* ===== Sync Flags (Pony-derived) ===== */

#define MS_ACTOR_OVERLOADED     0x01  /* mailbox non-empty after batch */
#define MS_ACTOR_UNDER_PRESSURE 0x02  /* application-level backpressure */
#define MS_ACTOR_MUTED          0x04  /* paused by scheduler (target overloaded) */
#define MS_ACTOR_BLOCKED        0x08  /* idle + RC > 0 (cycle detection candidate) */
#define MS_ACTOR_CYCLE_MARKED   0x10  /* internal: marked for cycle collection (do not reuse MUTED) */
#define MS_ACTOR_SUSPENDED      0x20  /* Phase 5: actor awaiting spawn completion (cooperative) */

/* ===== Actor Struct ===== */

typedef struct msActor {
    msMpscQueue mailbox;          /* Lock-free MPSC message queue */
    msActorDispatchFn dispatch;   /* Message handler (generated by compiler) */
    void* state;                  /* Pointer to actor's data struct (Ref<T>) */
    int32_t schedulerID;          /* Pinned scheduler index */
    int64_t pid;                  /* I19: [gen:27|slot:26] table handle (53-bit, double-exact) */
    int32_t pidSlot;              /* I19: slot index into the pid table */
    _Atomic(uint8_t) syncFlags;   /* Backpressure + lifecycle flags */
    _Atomic(bool) hasWork;        /* Set on push, cleared after drain */
    _Atomic(bool) processing;     /* CAS guard: only one thread may process at a time (enables work stealing) */
    _Atomic(bool) scheduled;      /* Pony parity: true = in run queue or being processed. Prevents double-enqueue. */
    _Atomic(struct msActor*) runNext;  /* Intrusive run queue link (lock-free stack per scheduler) */
    /* Muting: pids of actors paused because this actor is overloaded (I19: pids,
     * never pointers — a muted sender may be reaped while in this list) */
    int64_t* mutedBy;
    int mutedByCount;
    int mutedByCap;
    /* Cycle detection: pids this actor references (I19: pids — CD walks these
     * cross-scheduler, referents may be reaped at any time) */
    int64_t* refs;
    int refsCount;
    int refsCap;
    /* Supervision: lifecycle callback (Erlang OTP onTerminate) */
    msActorOnTerminateFn onTerminateFn;
    /* Links: bidirectional exit propagation, stored as pids (I19/BEAM parity) */
    int64_t* links;
    int linkCount;
    int linkCap;
    bool trapExits;  /* true = receive EXIT as message instead of dying */
    /* System message handler: routes EXIT/DOWN to onExit/onDown methods */
    msActorSystemMsgFn onSystemMsg;
    /* Monitors: unidirectional DOWN messages (Erlang-style) */
    int64_t* monitorWatchers;           /* watcher pids (I19: pids, never pointers) */
    int64_t* monitorRefs;               /* monitor reference per watcher (for matching) */
    int monitorCount;
    int monitorCap;
    /* Idle timeout: fires onIdle system message (kind=-3) after N ms of no messages */
    int64_t idleTimeoutMs;     /* 0 = disabled (default via calloc) */
    int64_t lastActivityMs;    /* monotonic timestamp of last message receipt */
    /* Alive guard: prevents double-stop / use-after-free on dangling pid */
    _Atomic(bool) alive;
    /* Phase 5: cooperative suspension during spawn-inside-actor.
     * suspendedFut != NULL also holds the I18 reap gate closed: the resume
     * callback's LAST shell store clears it (release), so the reaper's acquire
     * proves the callback is done with the shell. */
    _Atomic(void*) suspendedFut;  /* msFuture* from async _impl (NULL = not suspended) */
    void* suspendedReplyFut;      /* CALL reply future (NULL for SEND). Used by R1 stop. */
    /* Phase 6 R1: out-of-band stop — supervisor can kill suspended actor without mailbox */
    _Atomic(bool) stopRequested;
    _Atomic(int32_t) stopReason;  /* written before the stopRequested acq_rel exchange */
} msActor;

/* ===== Batch Size ===== */

#define MS_ACTOR_BATCH 64

/* System message kinds: -1 EXIT, -2 DOWN, -3 onIdle, -4 STOP signal.
 * STOP is runtime-internal — swallowed by the batch loop, never routed to
 * user handlers; its only job is scheduling a visit whose gate reaps. */
#define MS_ACTOR_MSG_STOP (-4)

/* ===== Thread-local: currently executing actor (NULL if non-actor code) ===== */

#ifndef MS_THREAD_LOCAL
#ifdef _WIN32
#define MS_THREAD_LOCAL __declspec(thread)
#else
#define MS_THREAD_LOCAL _Thread_local
#endif
#endif

/* Shared TLS / globals — defined in runtime/actor/actor.c. Extern (not
 * static) so all .ms→.c TUs see the same instance — see actor.c header. */
extern MS_THREAD_LOCAL msActor* msCurrentActor;
extern MS_THREAD_LOCAL int msMySchedulerID;

/* ===== I19: Pid Table + Hazard Pins =====
 *
 * A pid is [generation:27 | slot:26] packed into 53 bits — double-exact, because
 * pids ride EXIT/DOWN payloads as doubles. Slots live in lazily-allocated fixed
 * segments (never freed or moved, so slot pointers are stable). Lookup validates
 * the generation and pins the shell in a per-thread hazard slot; teardown bumps
 * the generation first (new lookups fail), then frees — deferred to the owner's
 * reap scan while any in-flight lookup still pins the shell. BEAM process-table
 * semantics; hazard pins stand in for BEAM's thread-progress. */

#define MS_PID_SLOT_BITS 26
#define MS_PID_GEN_MASK ((1ull << 27) - 1)
#define MS_PID_SLOT_MASK ((1u << MS_PID_SLOT_BITS) - 1)
#define MS_PID_SEG_BITS 12
#define MS_PID_SEG_SIZE (1 << MS_PID_SEG_BITS)
#define MS_PID_SEG_COUNT (1 << (MS_PID_SLOT_BITS - MS_PID_SEG_BITS))

typedef struct msPidSlot {
    _Atomic(uint64_t) gen;      /* full counter; low 27 bits ride in the pid */
    _Atomic(void*) ptr;         /* msActor* while live, NULL while dead */
    _Atomic(int32_t) nextFree;  /* free-list link (slot index, -1 = end) */
} msPidSlot;

extern _Atomic(msPidSlot*) msPidSegs[MS_PID_SEG_COUNT];
extern _Atomic(uint64_t) msPidFreeHead;  /* [aba:32 | slotIdx+1:32]; low32==0 = empty */
extern _Atomic(int32_t) msPidNextSlot;
extern pthread_mutex_t msPidSegLock;

#define MS_HAZARD_SLOTS 2  /* max simultaneous pins per thread: link/monitor hold 2 */
typedef struct msHazardRec {
    _Atomic(void*) slot[MS_HAZARD_SLOTS];
    _Atomic(struct msHazardRec*) next;
} msHazardRec;
extern _Atomic(msHazardRec*) msHazardHead;
extern MS_THREAD_LOCAL msHazardRec* msMyHazard;

static inline msPidSlot* msPidSlotAt(int32_t idx) {
    msPidSlot* seg = atomic_load_explicit(&msPidSegs[idx >> MS_PID_SEG_BITS], memory_order_acquire);
    return &seg[idx & (MS_PID_SEG_SIZE - 1)];
}

static inline int32_t msPidSlotClaim(void) {
    uint64_t head = atomic_load_explicit(&msPidFreeHead, memory_order_acquire);
    while ((uint32_t)head != 0u) {
        int32_t idx = (int32_t)((uint32_t)head - 1u);
        int32_t next = atomic_load_explicit(&msPidSlotAt(idx)->nextFree, memory_order_relaxed);
        uint64_t newHead = (((head >> 32) + 1) << 32) | (uint32_t)(next + 1);
        if (atomic_compare_exchange_weak_explicit(&msPidFreeHead, &head, newHead,
                memory_order_acq_rel, memory_order_acquire)) return idx;
    }
    int32_t idx = atomic_fetch_add(&msPidNextSlot, 1);
    int segI = idx >> MS_PID_SEG_BITS;
    if (atomic_load_explicit(&msPidSegs[segI], memory_order_acquire) == NULL) {
        pthread_mutex_lock(&msPidSegLock);
        if (atomic_load_explicit(&msPidSegs[segI], memory_order_relaxed) == NULL) {
            atomic_store_explicit(&msPidSegs[segI],
                (msPidSlot*)calloc(MS_PID_SEG_SIZE, sizeof(msPidSlot)), memory_order_release);
        }
        pthread_mutex_unlock(&msPidSegLock);
    }
    return idx;
}

static inline msHazardRec* msHazardEnsure(void) {
    msHazardRec* h = msMyHazard;
    if (h != NULL) return h;
    h = (msHazardRec*)calloc(1, sizeof(msHazardRec));
    msHazardRec* head = atomic_load_explicit(&msHazardHead, memory_order_relaxed);
    do {
        atomic_store_explicit(&h->next, head, memory_order_relaxed);
    } while (!atomic_compare_exchange_weak_explicit(&msHazardHead, &head, h,
            memory_order_release, memory_order_relaxed));
    msMyHazard = h;
    return h;
}

/* Clear this thread's pin on p. No-op if not pinned — every runtime call that
 * receives a FromPid result clears on every exit, so double-clears are normal. */
static inline void msHazardClear(void* p) {
    msHazardRec* h = msMyHazard;
    if (h == NULL || p == NULL) return;
    for (int i = 0; i < MS_HAZARD_SLOTS; i++) {
        if (atomic_load_explicit(&h->slot[i], memory_order_relaxed) == p) {
            atomic_store_explicit(&h->slot[i], NULL, memory_order_release);
        }
    }
}

static inline bool msHazardScan(void* p) {
    for (msHazardRec* h = atomic_load_explicit(&msHazardHead, memory_order_acquire);
         h != NULL; h = atomic_load_explicit(&h->next, memory_order_acquire)) {
        for (int i = 0; i < MS_HAZARD_SLOTS; i++) {
            if (atomic_load_explicit(&h->slot[i], memory_order_acquire) == p) return true;
        }
    }
    return false;
}

static inline int64_t msPidPublish(msActor* a) {
    int32_t idx = msPidSlotClaim();
    msPidSlot* s = msPidSlotAt(idx);
    uint64_t g = atomic_load_explicit(&s->gen, memory_order_relaxed) + 1;
    if ((g & MS_PID_GEN_MASK) == 0) g++;  /* keep the packed pid nonzero (0 = null pid) */
    atomic_store_explicit(&s->gen, g, memory_order_relaxed);
    a->pid = (int64_t)(((g & MS_PID_GEN_MASK) << MS_PID_SLOT_BITS) | (uint64_t)(uint32_t)idx);
    a->pidSlot = idx;
    atomic_store_explicit(&s->ptr, a, memory_order_release);
    return a->pid;
}

/* Invalidate the slot: new lookups fail from here on. Owner-thread teardown only. */
static inline void msPidRelease(msActor* a) {
    msPidSlot* s = msPidSlotAt(a->pidSlot);
    atomic_store_explicit(&s->ptr, NULL, memory_order_relaxed);
    atomic_fetch_add_explicit(&s->gen, 1, memory_order_release);
    uint64_t head = atomic_load_explicit(&msPidFreeHead, memory_order_relaxed);
    uint64_t newHead;
    do {
        atomic_store_explicit(&s->nextFree, (int32_t)((uint32_t)head) - 1, memory_order_relaxed);
        newHead = (((head >> 32) + 1) << 32) | (uint32_t)(a->pidSlot + 1);
    } while (!atomic_compare_exchange_weak_explicit(&msPidFreeHead, &head, newHead,
            memory_order_release, memory_order_relaxed));
}

/* Pid → shell. Generation-validated + hazard-pinned; NULL for dead/reused slots.
 * The pin ends inside the runtime call the result flows into — msActorSend,
 * msActorSuspend, msActorStop, etc. all msHazardClear on every exit. */
static inline msActor* msActorFromPid(int64_t pid) {
    if (pid <= 0) return NULL;
    int32_t idx = (int32_t)((uint64_t)pid & MS_PID_SLOT_MASK);
    uint64_t g = ((uint64_t)pid >> MS_PID_SLOT_BITS) & MS_PID_GEN_MASK;
    if (idx >= atomic_load_explicit(&msPidNextSlot, memory_order_acquire)) return NULL;
    msPidSlot* s = msPidSlotAt(idx);
    void* p = atomic_load_explicit(&s->ptr, memory_order_acquire);
    if (p == NULL || (atomic_load_explicit(&s->gen, memory_order_acquire) & MS_PID_GEN_MASK) != g)
        return NULL;
    msHazardRec* h = msHazardEnsure();
    int k = -1;
    for (int i = 0; i < MS_HAZARD_SLOTS; i++) {
        if (atomic_load_explicit(&h->slot[i], memory_order_relaxed) == NULL) { k = i; break; }
    }
    if (k < 0) return NULL;  /* both slots pinned (impossible by enumeration) — fail safe */
    atomic_store_explicit(&h->slot[k], p, memory_order_seq_cst);
    /* Re-validate after publish (hazard handshake vs. the reaper's gen bump). */
    if ((atomic_load_explicit(&s->gen, memory_order_seq_cst) & MS_PID_GEN_MASK) != g
            || atomic_load_explicit(&s->ptr, memory_order_relaxed) != p) {
        atomic_store_explicit(&h->slot[k], NULL, memory_order_release);
        return NULL;
    }
    return (msActor*)p;
}

/* Pin a live table slot by index (any generation) — CD's global iteration. */
static inline msActor* msPidPinSlot(int32_t idx) {
    msPidSlot* s = msPidSlotAt(idx);
    void* p = atomic_load_explicit(&s->ptr, memory_order_acquire);
    if (p == NULL) return NULL;
    uint64_t g = atomic_load_explicit(&s->gen, memory_order_acquire);
    msHazardRec* h = msHazardEnsure();
    int k = -1;
    for (int i = 0; i < MS_HAZARD_SLOTS; i++) {
        if (atomic_load_explicit(&h->slot[i], memory_order_relaxed) == NULL) { k = i; break; }
    }
    if (k < 0) return NULL;
    atomic_store_explicit(&h->slot[k], p, memory_order_seq_cst);
    if (atomic_load_explicit(&s->gen, memory_order_seq_cst) != g
            || atomic_load_explicit(&s->ptr, memory_order_relaxed) != p) {
        atomic_store_explicit(&h->slot[k], NULL, memory_order_release);
        return NULL;
    }
    return (msActor*)p;
}

/* ===== Flag Helpers ===== */

static inline uint8_t msActorGetFlags(msActor* a) {
    return atomic_load_explicit(&a->syncFlags, memory_order_acquire);
}

static inline void msActorSetFlag(msActor* a, uint8_t flag) {
    atomic_fetch_or_explicit(&a->syncFlags, flag, memory_order_release);
}

static inline void msActorClearFlag(msActor* a, uint8_t flag) {
    atomic_fetch_and_explicit(&a->syncFlags, (uint8_t)~flag, memory_order_release);
}

static inline bool msActorHasFlag(msActor* a, uint8_t flag) {
    return (msActorGetFlags(a) & flag) != 0;
}

/* ===== Muting ===== */

/* Mute a sender because the receiver is overloaded. */
static inline void msActorMute(msActor* sender, msActor* receiver) {
    if (sender == NULL || sender == receiver) return;
    if (msActorHasFlag(sender, MS_ACTOR_MUTED)) return;
    msActorSetFlag(sender, MS_ACTOR_MUTED);
    /* Track who we muted so we can unmute them later (grow on demand) */
    if (receiver->mutedByCount >= receiver->mutedByCap) {
        int newCap = receiver->mutedByCap == 0 ? 4 : receiver->mutedByCap * 2;
        receiver->mutedBy = (int64_t*)realloc(receiver->mutedBy, newCap * sizeof(int64_t));
        receiver->mutedByCap = newCap;
    }
    receiver->mutedBy[receiver->mutedByCount++] = sender->pid;
}

/* Unmute all actors that were muted because this actor was overloaded. */
static inline void msActorUnmuteAll(msActor* receiver) {
    for (int i = 0; i < receiver->mutedByCount; i++) {
        msActor* m = msActorFromPid(receiver->mutedBy[i]);
        if (m != NULL) {
            msActorClearFlag(m, MS_ACTOR_MUTED);
            msHazardClear(m);
        }
        receiver->mutedBy[i] = 0;
    }
    receiver->mutedByCount = 0;
}

/* ===== Actor Lifecycle ===== */

static inline msActor* msActorCreate(void* state, msActorDispatchFn dispatch) {
    msActor* a = (msActor*)calloc(1, sizeof(msActor));
    msMpscInit(&a->mailbox);
    a->dispatch = dispatch;
    a->state = state;
    a->schedulerID = 0;
    atomic_store_explicit(&a->syncFlags, 0, memory_order_relaxed);
    atomic_store_explicit(&a->hasWork, false, memory_order_relaxed);
    atomic_store_explicit(&a->processing, false, memory_order_relaxed);
    atomic_store_explicit(&a->scheduled, false, memory_order_relaxed);
    atomic_store_explicit(&a->runNext, NULL, memory_order_relaxed);
    a->mutedBy = NULL;
    a->mutedByCount = 0;
    a->mutedByCap = 0;
    a->refs = NULL;
    a->refsCount = 0;
    a->refsCap = 0;
    a->onTerminateFn = NULL;
    a->onSystemMsg = NULL;
    a->links = NULL;
    a->linkCount = 0;
    a->linkCap = 0;
    a->trapExits = false;
    a->monitorWatchers = NULL;
    a->monitorRefs = NULL;
    a->monitorCount = 0;
    a->monitorCap = 0;
    atomic_store_explicit(&a->alive, true, memory_order_relaxed);
    msPidPublish(a);
    return a;
}

/* Create actor and return its pid (for the typed pid field in the actor struct) */
static inline int64_t msActorCreatePid(void* state, msActorDispatchFn dispatch) {
    return msActorCreate(state, dispatch)->pid;
}

/* ===== Multi-Scheduler (forward declarations needed by msActorSend) ===== */

#define MS_SCHED_INIT_CAP 256   /* initial actor slots per scheduler (grows on demand) */
#define MS_MAX_SCHEDULERS 64

typedef struct msSchedActors {
    msActor** actors;             /* heap-allocated, grows on demand (NULL until first actor) */
    int cap;                      /* current capacity (0 = uninitialized) */
    _Atomic(int) count;           /* atomic: CD reads while main thread may register */
    int pollCount;                /* for periodic cycle detection (scheduler 0 only) */
    _Atomic(msActor*) runHead;    /* lock-free run queue: actors with pending messages */
    msActor* deferredFree;        /* I19: hazard-pinned shells awaiting free (owner thread only) */
    _Atomic(bool) wakeAmortized;  /* amortize wakes: true = worker already woken, skip syscall.
                                   * Removed Apr 8 (5122d20) citing "missed wakes / 500ms stalls" but
                                   * restored Apr 20 after Pony-design review: the claim conflated
                                   * two separate flags; the real race is bounded by selector re-poll.
                                   * Required for O(schedulers) wakes instead of O(actors) at 1M+. */
} msSchedActors;

extern msSchedActors msSchedulers[MS_MAX_SCHEDULERS];
extern int msSchedulerCount;

/* Push actor onto scheduler's run queue (any thread, lock-free). O(1). */
static inline void msSchedRunPush(msSchedActors* sched, msActor* a) {
    msActor* head = atomic_load_explicit(&sched->runHead, memory_order_relaxed);
    do {
        atomic_store_explicit(&a->runNext, head, memory_order_relaxed);
    } while (!atomic_compare_exchange_weak_explicit(&sched->runHead, &head, a,
        memory_order_release, memory_order_relaxed));
}

/* Pop one actor from scheduler's run queue (any thread, lock-free CAS). O(1). */
static inline msActor* msSchedRunPop(msSchedActors* sched) {
    msActor* head = atomic_load_explicit(&sched->runHead, memory_order_acquire);
    while (head != NULL) {
        msActor* next = atomic_load_explicit(&head->runNext, memory_order_relaxed);
        if (atomic_compare_exchange_weak_explicit(&sched->runHead, &head, next,
                memory_order_acq_rel, memory_order_acquire)) {
            atomic_store_explicit(&head->runNext, NULL, memory_order_relaxed);
            return head;
        }
    }
    return NULL;
}

/* Global counter: number of actors with idle timeouts. Scan skipped when 0. */
extern _Atomic(int) msActorsWithTimeout;
/* Global counter: stop-flagged actors not yet reaped. Reap scan skipped when 0. */
extern _Atomic(int) msActorsStopPending;

/* Forward declarations for wake routing */
extern void msActorWakeEventLoop(void);  /* dispatch.c */
extern void msEnsureWakePipe(void);      /* dispatch.c — init wake pipe early for actor sends */
extern void msPoolWakeWorker(int schedulerID);  /* pool.c — targeted, no spurious wakeups */
extern void msSetActorIdleCap(int ms);  /* dispatch.c — caps event loop sleep for idle timeouts */

/* Forward declarations */
static inline void msCDInit(void);
static inline void msCDTick(void);
static inline void msActorRemoveLink(msActor* a, int64_t targetPid);
static inline void msActorStop(int64_t pid, int32_t reason);
static inline void msActorUnregisterByPtr(msActor* a);
static inline void msActorDestroyWithReason(msActor* a, int32_t reason);

/* ===== CALL reply completion plumbing (Amendment G / I15 / I16) =====
 *
 * A CALL reply future crosses threads: the sender (owner thread) creates it,
 * the actor-processing thread (a pool worker for scheduler N) completes it,
 * and the awaiting owner reads and destroys it. Two invariants apply:
 *
 *  I16 (Amendment G): the in-flight ref is taken on the SENDER thread inside
 *  msActorSend, before the message becomes visible in the mailbox
 *  (acquire-before-visible). The completers below push via
 *  msCompletionQueuePushOwned — no worker-side incref, ever.
 *
 *  I15 (Amendment A): callbacks fire on the dispatcher DRAIN, never inline on
 *  the actor-processing worker. Before this, msMsgComplete* fired inline and
 *  the awaiting owner could observe `finished`, read the value, and destroy
 *  the future while the worker was still inside msFutureFireCallbacks —
 *  heap-use-after-free (SAN lane, 409/411, flaky under timing).
 *
 * Single-threaded builds (wasm/emcc, MS_FUTURE_SUBMIT_REF == 0) keep the old
 * inline fire: there is no second thread, so I15/I16 have nothing to order. */

/* Defined in the dispatch backends (dispatchFull.c / dispatchEmcc.c /
 * dispatchWasm.c) — declared here because actor.h sits above thread.h in
 * the include graph. */
extern void msCompletionQueuePushOwned(void* fut, bool isFail, void* error);
extern void msCompletionQueuePushReleaseBatch(void** futs, int count);

/* Publish path tail used by msMsgComplete*: the value is already stored and
 * `finished` is already release-stored (blocked waiters may read NOW — same
 * split-completion Step 1 as thread.h's spawn workers); only the callback
 * volley is routed. */
static inline void msMsgReplyDispatch(void* fut) {
#if MS_FUTURE_SUBMIT_REF
    msCompletionQueuePushOwned(fut, false, NULL);
#else
    msFutureFireCallbacks((msFutureBase*)fut);
#endif
}

/* Fail a CALL reply from any fail site (stop-during-suspend, teardown drain)
 * and release the mailbox's in-flight ref. The release is DEFERRED through
 * the completion queue (Amendment H): these sites can run on an actor-
 * processing worker, and an inline decref would race the awaiting owner on
 * the future's non-atomic rc. msFutureFail still fires inline so a blocked
 * waiter unblocks immediately (I20 {noproc}); async steppers registered on
 * the finished future re-fire through msFutureAddCallback's finished-path. */
static inline void msMsgReplyFail(void* fut) {
    if (fut == NULL) return;
    msFutureFail(fut, NULL);
#if MS_FUTURE_SUBMIT_REF
    void* f = fut;
    msCompletionQueuePushReleaseBatch(&f, 1);
#endif
}

/* ===== Phase 5: Cooperative Actor Suspension ===== */

/* Resume callback: re-enqueues actor on scheduler after spawn completion.
 * Signature matches msClosureFn (void*, ...) — called by msFutureFireCallbacks.
 * I18: the reap gate stays closed while suspendedFut is non-NULL, so every shell
 * dereference here happens-before any reap. On the stopped lane the LAST shell
 * store is the suspendedFut=NULL release; after it, only non-shell wakes. */
static inline void msActorResumeFromFut(void* rawActor, ...) {
    msActor* a = (msActor*)rawActor;
    int sid = a->schedulerID;
    if (atomic_load_explicit(&a->stopRequested, memory_order_acquire)) {
        /* Stopped lane: MS_ACTOR_SUSPENDED stays SET. It is the latch that keeps
         * senders off the wasEmpty edge, so no run-queue entry can exist when the
         * reap scan frees this shell (scheduled alone can't prove that — a
         * markEmpty/push race can overwrite a sender's scheduled=true). */
        /* R1: stop arrived during suspension — don't resume the method. Fail the
         * CALL reply so callers unblock, open the reap gate, wake the owner's
         * reap scan. Never reap here: a stale queue entry's visit may hold the
         * shell, and the reaper must be the owner scheduler. */
        if (a->suspendedReplyFut != NULL) {
            msMsgReplyFail(a->suspendedReplyFut);
        }
        a->suspendedReplyFut = NULL;
        atomic_store_explicit(&a->suspendedFut, NULL, memory_order_release);
        if (sid == 0) msActorWakeEventLoop();
        else msPoolWakeWorker(sid);
        return;
    }
    msActorClearFlag(a, MS_ACTOR_SUSPENDED);
    /* Normal resume: suspendedFut stays set — the visit clears it (gate stays
     * closed until the visit owns the shell under processing). Re-enqueue on the
     * run queue (Pony parity: CAS prevents double-push vs a concurrent send). */
    {
        bool exp = false;
        if (atomic_compare_exchange_strong_explicit(&a->scheduled, &exp, true,
                memory_order_acq_rel, memory_order_relaxed)) {
            if (sid >= 0 && sid < msSchedulerCount) {
                msSchedRunPush(&msSchedulers[sid], a);
            }
            if (sid == 0) msActorWakeEventLoop();
            else msPoolWakeWorker(sid);
        }
    }
}

/* Suspend actor: save async _impl future, register resume callback.
 * For CALL methods, replyFut is chained separately by the dispatch function. */
static inline void msActorSuspend(msActor* a, void* implFut, void* replyFut) {
    if (a == NULL) return;
    /* R1 entry check: stop won the race to the suspend point — fail the reply,
     * don't suspend, register no resume callback (no shell reference outlives
     * this call). The visit's reap gate collects on the next pass. */
    if (atomic_load_explicit(&a->stopRequested, memory_order_acquire)) {
        if (replyFut != NULL) msMsgReplyFail(replyFut);
        msHazardClear(a);
        return;
    }
    a->suspendedReplyFut = replyFut;
    atomic_store_explicit(&a->suspendedFut, implFut, memory_order_release);
    msActorSetFlag(a, MS_ACTOR_SUSPENDED);
    /* When implFut completes, resume the actor on its scheduler. From here the
     * suspendedFut gate (I18) keeps the shell reachable-safe, not the pin. */
    msFutureAddCallback(implFut, (msClosure){
        .fn = (msClosureFn)msActorResumeFromFut,
        .env = (void*)a
    });
    msHazardClear(a);
}

/* Name registry data (forward declaration — functions defined after monitors section) */
#define MS_NAME_REGISTRY_INIT_CAP 256
typedef struct { msString name; int64_t pid; } msNameEntry;
extern msNameEntry* msNameRegistry;
extern int msNameRegistryCap;
extern int msNameRegistryCount;
extern pthread_mutex_t msNameRegistryLock;

/* Lazy init: allocate on first use, zero-cost if name registry is never used */
static inline void msNameRegistryEnsure(void) {
    if (msNameRegistry != NULL) return;
    msNameRegistryCap = MS_NAME_REGISTRY_INIT_CAP;
    msNameRegistry = (msNameEntry*)calloc(msNameRegistryCap, sizeof(msNameEntry));
}

/* Grow and rehash when load factor exceeds 75%. Must hold lock. */
static inline void msNameRegistryGrow(void) {
    int oldCap = msNameRegistryCap;
    msNameEntry* oldTable = msNameRegistry;
    msNameRegistryCap = oldCap * 2;
    msNameRegistry = (msNameEntry*)calloc(msNameRegistryCap, sizeof(msNameEntry));
    msNameRegistryCount = 0;
    /* Rehash all entries into new table */
    for (int i = 0; i < oldCap; i++) {
        if (oldTable[i].pid == 0) continue;
        uint32_t h = (uint32_t)msStringHash(oldTable[i].name) & (msNameRegistryCap - 1);
        for (int k = 0; k < msNameRegistryCap; k++) {
            uint32_t s = (h + k) & (msNameRegistryCap - 1);
            if (msNameRegistry[s].pid == 0) {
                msNameRegistry[s] = oldTable[i];
                msNameRegistryCount++;
                break;
            }
        }
    }
    free(oldTable);
}

/* Hook: auto-unregister on destroy (stored in dispatch.c — shared across TUs) */
extern void msSetActorDestroyHook(void (*hook)(void*));
extern void msCallActorDestroyHook(void* actor);

/*
 * Send a message to an actor (any thread, wait-free).
 * If receiver is overloaded, mutes the current actor (sender).
 */
static inline void msActorSend(msActor* a, msMessage* msg) {
    /* Guard: null actor (DRC scope cleanup or uninitialized) */
    if (a == NULL) {
        /* I20: a CALL to a stale/dead pid must fail its reply future (BEAM {noproc})
         * so the awaiting caller unblocks instead of hanging. SEND has no reply. */
        if (msg->replyFuture != NULL) msFutureFail(msg->replyFuture, NULL);
        msMsgFree(msg);
        return;
    }
    /* Guard: don't send to dead actor (prevents use-after-free on freed mailbox) */
    if (!atomic_load_explicit(&a->alive, memory_order_acquire)) {
        if (msg->replyFuture != NULL) msFutureFail(msg->replyFuture, NULL);
        msMsgFree(msg);
        msHazardClear(a);
        return;
    }
    /* Amendment G (I16) for actor CALLs — acquire-before-visible. The reply
     * future's in-flight ref is taken HERE, on the sender's thread, before
     * the message becomes visible in the mailbox. The actor-processing
     * thread (a pool worker for scheduler N) then publishes value+finished
     * and routes the callback volley through msCompletionQueuePushOwned —
     * no worker-side incref ever touches the non-atomic rc. The drain
     * releases this ref after msFutureFireCallbacks; every fail site that
     * pops the message pairs with msMsgReplyFail's deferred release.
     * MUST stay after the two guards above: they fail the reply before any
     * ref exists, and msMsgReplyFail would over-release it. */
#if MS_FUTURE_SUBMIT_REF
    if (msg->replyFuture != NULL) {
        msIncRef(msg->replyFuture);
        ((msFutureBase*)msg->replyFuture)->crossThreadPublished = true;
    }
#endif
    bool wasEmpty = msMpscPush(&a->mailbox, msg);
    atomic_store_explicit(&a->hasWork, true, memory_order_release);

    /* Backpressure: if receiver overloaded, mute sender */
    if (msActorHasFlag(a, MS_ACTOR_OVERLOADED) && msCurrentActor != NULL) {
        msActorMute(msCurrentActor, a);
    }

    /* Pony messageq gate: schedule iff this push transitioned the mailbox empty→non-empty.
     * wasEmpty is atomic with the processing thread's markEmpty, so exactly one party (this
     * sender, or the processing thread's re-enqueue) schedules the actor — no stale-flag
     * window (the old scheduled-CAS could observe scheduled=false mid-deschedule and push the
     * actor onto a run queue while it was still being processed, so a popper popped it, failed
     * the processing CAS, and dropped it = strand), and no double-enqueue (only the
     * empty→non-empty edge pushes). A SUSPENDED actor is re-scheduled by its resume path. */
    if (wasEmpty && !msActorHasFlag(a, MS_ACTOR_SUSPENDED)) {
        atomic_store_explicit(&a->scheduled, true, memory_order_release);
        int sid = a->schedulerID;
        if (sid >= 0 && sid < msSchedulerCount) {
            msSchedRunPush(&msSchedulers[sid], a);
            /* Amortized wake: skip the wake syscall if this scheduler was already woken since
             * its last drain — O(schedulers) wakes instead of O(actors) at high send rates. */
            if (!atomic_exchange_explicit(&msSchedulers[sid].wakeAmortized, true,
                    memory_order_acq_rel)) {
                if (sid == 0) msActorWakeEventLoop();
                else msPoolWakeWorker(sid);
            }
        }
    }
    msHazardClear(a);
}

/*
 * Process up to `maxBatch` messages from the actor's mailbox.
 * Sets/clears OVERLOADED flag. Triggers unmute when caught up.
 */
static inline int msActorProcess(msActor* a, int maxBatch) {
    /* Dead actor guard — may be in run queue from before destruction */
    if (!atomic_load_explicit(&a->alive, memory_order_acquire)) return 0;
    /* CAS guard: only one thread may process this actor at a time.
     * Enables work stealing — any idle thread can safely call this. */
    bool expected = false;
    if (!atomic_compare_exchange_strong_explicit(&a->processing, &expected, true,
            memory_order_acquire, memory_order_relaxed)) {
        /* Another thread holds processing AND the actor is on a run queue (a sender's
         * wasEmpty push landed in that thread's deschedule window, between its markEmpty and
         * its processing release). We already popped it off the queue, so re-enqueue it
         * instead of dropping it: the holder's deschedule branch does NOT re-push, so a drop
         * here would strand the pending message. No double-push — the CAS only fails inside
         * that window, where the holder never re-pushes; a later pop wins the freed CAS. */
        if (a->schedulerID >= 0 && a->schedulerID < msSchedulerCount) {
            msSchedRunPush(&msSchedulers[a->schedulerID], a);
            if (a->schedulerID == 0) msActorWakeEventLoop();
            else msPoolWakeWorker(a->schedulerID);
        }
        return 0;
    }

    msActor* prevActor = msCurrentActor;
    msCurrentActor = a;

    /* Phase 5: check for pending suspension before draining mailbox */
    {
        void* sfp = atomic_load_explicit(&a->suspendedFut, memory_order_acquire);
        if (sfp != NULL) {
            msFutureBase* sf = (msFutureBase*)sfp;
            bool resumed = atomic_load_explicit(&sf->finished, memory_order_acquire);
            if (!resumed) {
                /* Still suspended — deschedule BEFORE releasing processing, or the
                 * resume callback's scheduled-CAS can never re-enqueue (strand). */
                atomic_store_explicit(&a->scheduled, false, memory_order_release);
                /* Re-check: resume may have completed between the loads — reclaim
                 * the visit (CAS back) or the mailbox stalls until the next send. */
                if (atomic_load_explicit(&sf->finished, memory_order_acquire)) {
                    bool reclaim = false;
                    resumed = atomic_compare_exchange_strong_explicit(&a->scheduled,
                        &reclaim, true, memory_order_acq_rel, memory_order_relaxed);
                }
                if (!resumed) {
                    msCurrentActor = prevActor;
                    atomic_store_explicit(&a->processing, false, memory_order_release);
                    return 0;
                }
            }
            /* Resumed: _impl stepper already completed the reply future via
             * msFutureChain. Clear suspension state, fall through to mailbox drain. */
            atomic_store_explicit(&a->suspendedFut, NULL, memory_order_release);
            a->suspendedReplyFut = NULL;
        }
    }

    /* I18 reap point: stop requested, suspension clear, we hold processing and the
     * only queue entry. The OWNER tears down and frees; a non-owner (steal) visit
     * hands the actor back so registry writes and free stay single-threaded. */
    if (atomic_load_explicit(&a->stopRequested, memory_order_acquire)) {
        int sid = a->schedulerID;
        msCurrentActor = prevActor;
        if (msMySchedulerID != sid) {
            atomic_store_explicit(&a->processing, false, memory_order_release);
            if (sid >= 0 && sid < msSchedulerCount) {
                msSchedRunPush(&msSchedulers[sid], a);
                if (sid == 0) msActorWakeEventLoop();
                else msPoolWakeWorker(sid);
            }
            return 0;
        }
        msActorDestroyWithReason(a,
            atomic_load_explicit(&a->stopReason, memory_order_relaxed));  /* frees a */
        return 0;
    }

    /* Clear BLOCKED — we're actively processing */
    msActorClearFlag(a, MS_ACTOR_BLOCKED);

    /* Reset idle timer on message receipt (Erlang: gen_server timeout resets on any message) */
    if (a->idleTimeoutMs > 0) {
        a->lastActivityMs = msMonoTimeMs();
    }

    int processed = 0;
    while (processed < maxBatch) {
        msMessage* msg = msMpscPop(&a->mailbox);
        if (msg == NULL) break;
        /* STOP signal: swallow — its scheduling job is done; the reap gate (or
         * the owner's reap scan) collects with the flag it rode in with. */
        if (msg->kind == MS_ACTOR_MSG_STOP) { processed++; continue; }
        /* System messages (kind < 0): route to onSystemMsg handler if set */
        if (msg->kind < 0 && a->onSystemMsg != NULL) {
            a->onSystemMsg(a->state, (void*)msg);
        } else {
            a->dispatch(a->state, (void*)msg);
        }
        /* Don't free msg here — MPSC pop made it the new tail stub.
         * It gets freed on the NEXT pop when a newer message takes its place. */
        processed++;
    }

    /* Scheduling decision, made WHILE HOLDING processing. Flags (heuristics) from the
     * pre-check; markEmpty is the LAST mailbox op and runs under processing so it shares the
     * single-consumer exclusion with msMpscPop (reading/CASing q->tail off-processing is the
     * two-consumer race). OVERLOADED/BLOCKED slightly-stale on a racing late message is
     * harmless. */
    bool emptyPre = msMpscIsEmpty(&a->mailbox);
    if (emptyPre) {
        if (msActorHasFlag(a, MS_ACTOR_OVERLOADED)) {
            msActorClearFlag(a, MS_ACTOR_OVERLOADED);
            msActorUnmuteAll(a);
        }
        if (a->state != NULL && msHeader(a->state)->rc > 0) {
            msActorSetFlag(a, MS_ACTOR_BLOCKED);
        }
    } else {
        msActorSetFlag(a, MS_ACTOR_OVERLOADED);
    }

    /* markEmpty: the LAST consumer op, under processing.
     *   TRUE  → truly empty → deschedule, NO re-push. A future sender's wasEmpty push
     *           re-queues it (atomic with markEmpty, so exactly one party schedules) — Pony parity.
     *   FALSE → a message is pending → re-enqueue, but DEFER the run-queue push to AFTER the
     *           processing release below, so a concurrent popper acquires processing only once
     *           we have let go (it wins the freed CAS, never drops). */
    bool reEnqueue;
    if (msMpscMarkEmpty(&a->mailbox)) {
        atomic_store_explicit(&a->hasWork, false, memory_order_release);
        atomic_store_explicit(&a->scheduled, false, memory_order_release);
        reEnqueue = false;
    } else {
        reEnqueue = true;
    }

    msCurrentActor = prevActor;
    atomic_store_explicit(&a->processing, false, memory_order_release);

    if (reEnqueue && a->schedulerID >= 0 && a->schedulerID < msSchedulerCount) {
        msSchedRunPush(&msSchedulers[a->schedulerID], a);
        if (a->schedulerID == 0) msActorWakeEventLoop();
        else msPoolWakeWorker(a->schedulerID);
    }

    msFutureReleaseFlush();
    return processed;
}

/* ===== Message Accessors (for dispatch functions generated by compiler) ===== */

static inline int32_t msMsgKind(void* msg) {
    return ((msMessage*)msg)->kind;
}

static inline void* msMsgReplyFuture(void* msg) {
    return ((msMessage*)msg)->replyFuture;
}

/* Future completion helpers — thin wrappers so dispatch can complete reply futures.
 * Split completion (same shape as thread.h's spawn workers): Step 1 stores the
 * value and release-stores `finished` — a blocked msWaitFor may read NOW; Step
 * 2 routes the callback volley to the dispatcher drain (msMsgReplyDispatch,
 * I15) — never fired inline on the actor-processing worker. */
static inline void msMsgCompleteDouble(void* fut, double val) {
    if (fut == NULL) return;
    msFuture_double* f = (msFuture_double*)fut;
    if (atomic_load_explicit(&f->base.finished, memory_order_acquire)) return;
    f->value = val;
    atomic_store_explicit(&f->base.finished, true, memory_order_release);
    msMsgReplyDispatch(fut);
}

/* Typed completers for integral and bool actor returns. Mirror Double: the
 * reply future was sized via msFutureCreate (msFuture_ptr layout, 8B value
 * slot); int and bool fit within that slot. The receive side uses
 * msFutureReadInt32/Int64/Bool which read from the SAME typed-struct offset,
 * so write side must use matching cast (msFuture_int32* etc.); otherwise
 * the byte pattern diverges (e.g. double 3.0 vs int32 3). */
static inline void msMsgCompleteInt32(void* fut, int32_t val) {
    if (fut == NULL) return;
    msFuture_int32* f = (msFuture_int32*)fut;
    if (atomic_load_explicit(&f->base.finished, memory_order_acquire)) return;
    f->value = val;
    atomic_store_explicit(&f->base.finished, true, memory_order_release);
    msMsgReplyDispatch(fut);
}

static inline void msMsgCompleteInt64(void* fut, int64_t val) {
    if (fut == NULL) return;
    msFuture_int64* f = (msFuture_int64*)fut;
    if (atomic_load_explicit(&f->base.finished, memory_order_acquire)) return;
    f->value = val;
    atomic_store_explicit(&f->base.finished, true, memory_order_release);
    msMsgReplyDispatch(fut);
}

static inline void msMsgCompleteBool(void* fut, bool val) {
    if (fut == NULL) return;
    msFuture_bool* f = (msFuture_bool*)fut;
    if (atomic_load_explicit(&f->base.finished, memory_order_acquire)) return;
    f->value = val;
    atomic_store_explicit(&f->base.finished, true, memory_order_release);
    msMsgReplyDispatch(fut);
}

static inline void msMsgCompletePtr(void* fut, void* val) {
    if (fut == NULL) return;
    msFuture* f = (msFuture*)fut;
    if (atomic_load_explicit(&f->base.finished, memory_order_acquire)) return;
    f->value = val;
    atomic_store_explicit(&f->base.finished, true, memory_order_release);
    msMsgReplyDispatch(fut);
}

static inline void msMsgCompleteString(void* fut, msString val) {
    if (fut == NULL) return;
    /* msString is 16 bytes — use msFuture_msString layout via MS_FUTURE_STRUCT.
     * Codegen emits MS_FUTURE_STRUCT(msFuture_msString, msString) for Promise<string>. */
    typedef struct { msFutureBase base; msString value; } msFuture_msString_local;
    msFuture_msString_local* f = (msFuture_msString_local*)fut;
    if (atomic_load_explicit(&f->base.finished, memory_order_acquire)) return;
    f->value = val;
    atomic_store_explicit(&f->base.finished, true, memory_order_release);
    msMsgReplyDispatch(fut);
}

static inline void msMsgCompleteVoid(void* fut) {
    if (fut == NULL) return;
    msFutureBase* f = (msFutureBase*)fut;
    if (atomic_load_explicit(&f->finished, memory_order_acquire)) return;
    atomic_store_explicit(&f->finished, true, memory_order_release);
    msMsgReplyDispatch(fut);
}

/* Set onTerminate callback (called by actorLower wiring).
 * Takes void* for fn to avoid function pointer type mismatch — _impl takes ActorType* not void*. */
static inline void msActorSetOnTerminate(void* actor, void* fn) {
    msActor* a = (msActor*)actor;
    if (a == NULL) return;
    a->onTerminateFn = (msActorOnTerminateFn)fn;
    msHazardClear(a);
}

/* Set system message handler (routes EXIT/DOWN to onExit/onDown methods). */
static inline void msActorSetSystemMsgHandler(void* actor, void* fn) {
    msActor* a = (msActor*)actor;
    if (a == NULL) return;
    a->onSystemMsg = (msActorSystemMsgFn)fn;
    msHazardClear(a);
}

static inline void msActorDestroyWithReason(msActor* a, int32_t reason) {
    /* Guard: prevent double-destroy (re-entrancy from link cascade or supervisor) */
    bool wasAlive = atomic_exchange_explicit(&a->alive, false, memory_order_acq_rel);
    if (!wasAlive) return;
    /* I19: release the pid slot FIRST — no new lookup reaches a dying shell.
     * Sends to this pid from onTerminate onward are cleanly dropped. */
    msPidRelease(a);
    /* Decrement idle timeout counter if this actor had a timeout */
    if (a->idleTimeoutMs > 0) {
        int remaining = atomic_fetch_sub(&msActorsWithTimeout, 1) - 1;
        if (remaining <= 0) msSetActorIdleCap(0);
    }
    /* Step 1: call onTerminate — actor is still alive, can send messages.
     * Skipped for MS_EXIT_KILLED (Erlang parity: brutal_kill skips terminate/2).
     * This prevents supervisor restart from hanging on a blocked onTerminate. */
    if (a->onTerminateFn != NULL && reason != MS_EXIT_KILLED) {
        a->onTerminateFn(a->state, reason);
    }
    /* Step 1.5: auto-unregister from name registry (Erlang: name freed after terminate/2) */
    msCallActorDestroyHook((void*)a);
    /* Step 2: propagate EXIT to linked actors (Erlang link semantics).
     * Links store pids — a linked actor already reaped is a clean skip. */
    for (int i = 0; i < a->linkCount; i++) {
        int64_t linkedPid = a->links[i];
        msActor* linked = msActorFromPid(linkedPid);
        if (linked == NULL) continue;
        msActorRemoveLink(linked, a->pid);  /* remove reverse link */
        if (linked->trapExits) {
            /* Trapping: deliver EXIT as a system message (kind = -1) */
            msMessage* exitMsg = msMsgAllocSized(-1, NULL, 2);
            msMsgSetDouble(exitMsg, 0, (double)a->pid);
            msMsgSetDouble(exitMsg, 1, (double)reason);  /* exit reason as double */
            msActorSend(linked, exitMsg);  /* send clears the pin */
        } else {
            /* Not trapping: cascade death (Erlang: linked process dies too) */
            msHazardClear(linked);
            msActorStop(linkedPid, reason);
        }
    }
    /* Step 3: send DOWN to monitors (Erlang: {'DOWN', Ref, process, Pid, Reason}) */
    for (int i = 0; i < a->monitorCount; i++) {
        msActor* watcher = msActorFromPid(a->monitorWatchers[i]);
        if (watcher == NULL) continue;
        msMessage* downMsg = msMsgAllocSized(-2, NULL, 3);  /* kind=-2: DOWN */
        msMsgSetDouble(downMsg, 0, (double)a->monitorRefs[i]);   /* monitor ref */
        msMsgSetDouble(downMsg, 1, (double)a->pid);
        msMsgSetDouble(downMsg, 2, (double)reason);  /* exit reason */
        msActorSend(watcher, downMsg);  /* send clears the pin */
    }
    /* Step 4: unmute senders */
    msActorUnmuteAll(a);
    /* Step 5: drain remaining messages. Do NOT free the popped message — pop
     * already made it the new tail stub (freed by the next pop, or by
     * msMpscDestroy below). Freeing it here threads the live tail into the
     * msg-pool free list and the drain chases pool nodes forever.
     * I20: fail each pending CALL's reply future (BEAM {noproc}) so callers
     * awaiting a now-reaped actor unblock instead of hanging. */
    {
        msMessage* dm;
        while ((dm = msMpscPop(&a->mailbox)) != NULL) {
            if (dm->replyFuture != NULL) msMsgReplyFail(dm->replyFuture);
        }
    }
    msMpscDestroy(&a->mailbox);
    if (a->mutedBy != NULL) free(a->mutedBy);
    if (a->links != NULL) free(a->links);
    if (a->monitorWatchers != NULL) free(a->monitorWatchers);
    if (a->monitorRefs != NULL) free(a->monitorRefs);
    if (a->refs != NULL) free(a->refs);
    /* Registry removal — I18: the reap runs on the owning scheduler's thread, so
     * each sched->actors[] keeps a single writer (stop() no longer removes). */
    if (a->schedulerID >= 0 && a->schedulerID < msSchedulerCount) {
        msSchedActors* schedR = &msSchedulers[a->schedulerID];
        int cntR = atomic_load_explicit(&schedR->count, memory_order_acquire);
        for (int iR = 0; iR < cntR; iR++) {
            if (schedR->actors[iR] == a) {
                schedR->actors[iR] = schedR->actors[cntR - 1];
                atomic_store_explicit(&schedR->count, cntR - 1, memory_order_release);
                break;
            }
        }
    }
    if (atomic_load_explicit(&a->stopRequested, memory_order_relaxed)) {
        atomic_fetch_sub(&msActorsStopPending, 1);
    }
    /* Sole owner: the handle is DRC-exempt (classify.ms) and the spawn-time msIncRef is
     * cycle-detector-only, so neither releases state — teardown frees it (Pony parity). */
    if (a->state != NULL) {
        const msTypeInfo* __st = msHeader(a->state)->type;
        if (__st != NULL && __st->destroyFn != NULL) __st->destroyFn(a->state);
        msDestroyAndDispose(a->state);
        a->state = NULL;
    }
    /* I19: defer the free while any in-flight lookup still pins the shell. The
     * pid slot is long released, so no NEW pin can appear — pins only drain. */
    if (msHazardScan(a)) {
        int sidD = (a->schedulerID >= 0 && a->schedulerID < msSchedulerCount) ? a->schedulerID : 0;
        atomic_store_explicit(&a->runNext, msSchedulers[sidD].deferredFree, memory_order_relaxed);
        msSchedulers[sidD].deferredFree = a;
    } else {
        free(a);
    }
}

static inline void msActorDestroy(msActor* a) {
    msActorDestroyWithReason(a, MS_EXIT_NORMAL);
}

/* Owner-thread synchronous reap drain: pop + process THIS scheduler's own run queue
 * only. Excludes work-stealing, cycle-detector ticks, and the idle-timeout scan (those
 * belong to the normal event-loop poll) — here we just let the owner's stopped actors
 * reach their reap gate, so a sync main that never re-enters the scheduler loop doesn't
 * accumulate stopped-actor state. */
static inline void msActorReapLocalQueue(void) {
    int id = msMySchedulerID;
    if (id < 0 || id >= msSchedulerCount) return;
    msSchedActors* sched = &msSchedulers[id];
    msActor* a;
    while ((a = msSchedRunPop(sched)) != NULL) {
        if (msActorHasFlag(a, MS_ACTOR_MUTED)) continue;
        msActorProcess(a, MS_ACTOR_BATCH);
    }
}

/* Stop an actor by pid — Erlang exit-signal semantics with Pony reap discipline
 * (I18): mark + wake; the OWNER scheduler tears down and frees at its next visit
 * or reap scan. Never destroys here — the shell may be a live run-queue node,
 * mid-process on another worker, or held as a pending resume-callback env. */
static inline void msActorStop(int64_t pid, int32_t reason) {
    msActor* a = msActorFromPid(pid);
    if (a == NULL) return;
    if (!atomic_load_explicit(&a->alive, memory_order_acquire)
            || atomic_load_explicit(&a->stopRequested, memory_order_acquire)) {
        msHazardClear(a);
        return;
    }
    atomic_store_explicit(&a->stopReason, reason, memory_order_relaxed);
    /* First stop wins; the exchange publishes stopReason (acq_rel). */
    if (atomic_exchange_explicit(&a->stopRequested, true, memory_order_acq_rel)) {
        msHazardClear(a);
        return;
    }
    atomic_fetch_add(&msActorsStopPending, 1);
    if (msActorHasFlag(a, MS_ACTOR_SUSPENDED)) {
        /* R1: suspended — flag only, never touch the mailbox. The resume callback
         * opens the reap gate; the owner's reap scan collects. */
        msHazardClear(a);
        return;
    }
    /* Awake/idle: the STOP signal rides the mailbox (R5 lane) so scheduling stays
     * on the wasEmpty edge — no new run-queue pusher, no double-enqueue. */
    int sid = a->schedulerID;
    msMessage* stopMsg = msMsgAllocSized(MS_ACTOR_MSG_STOP, NULL, 0);
    msActorSend(a, stopMsg);  /* send clears the pin — do not touch `a` after this */
    /* A synchronous owner (main = scheduler 0, not inside an actor behaviour) never
     * re-enters the scheduler loop, so I18's deferred owner reap would never run and
     * stopped actors' state would pile up unbounded. Force the owner's reap visit now:
     * routes through the same reap gate on the same owning thread — no new free path. */
    if (msCurrentActor == NULL && msMySchedulerID == sid) {
        msActorReapLocalQueue();
    }
}

/* ===== Actor References (for cycle detection) ===== */

static inline void msActorAddRef(msActor* from, msActor* to) {
    if (from == NULL || to == NULL || from == to) return;
    int64_t toPid = to->pid;
    /* Check for duplicate */
    for (int i = 0; i < from->refsCount; i++) {
        if (from->refs[i] == toPid) return;
    }
    /* Grow on demand */
    if (from->refsCount >= from->refsCap) {
        int newCap = from->refsCap == 0 ? 4 : from->refsCap * 2;
        from->refs = (int64_t*)realloc(from->refs, newCap * sizeof(int64_t));
        from->refsCap = newCap;
    }
    from->refs[from->refsCount++] = toPid;
}

/* ===== Links (bidirectional exit propagation, Erlang parity) ===== */

/* Add targetPid to a's link list (one direction). */
static inline void msActorAddLink(msActor* a, int64_t targetPid) {
    if (a == NULL || targetPid == 0 || a->pid == targetPid) return;
    for (int i = 0; i < a->linkCount; i++) {
        if (a->links[i] == targetPid) return;  /* already linked */
    }
    if (a->linkCount >= a->linkCap) {
        int newCap = a->linkCap == 0 ? 4 : a->linkCap * 2;
        a->links = (int64_t*)realloc(a->links, newCap * sizeof(int64_t));
        a->linkCap = newCap;
    }
    a->links[a->linkCount++] = targetPid;
}

/* Remove targetPid from a's link list (one direction). */
static inline void msActorRemoveLink(msActor* a, int64_t targetPid) {
    for (int i = 0; i < a->linkCount; i++) {
        if (a->links[i] == targetPid) {
            a->links[i] = a->links[a->linkCount - 1];
            a->linkCount--;
            return;
        }
    }
}

/* Bidirectional link (Erlang: link/1). Both pids must be live at link time. */
static inline void msActorLinkPid(int64_t pidA, int64_t pidB) {
    msActor* a = msActorFromPid(pidA);
    if (a == NULL) return;
    msActor* b = msActorFromPid(pidB);
    if (b == NULL) { msHazardClear(a); return; }
    msActorAddLink(a, pidB);
    msActorAddLink(b, pidA);
    msHazardClear(a);
    msHazardClear(b);
}

/* Bidirectional unlink. */
static inline void msActorUnlinkPid(int64_t pidA, int64_t pidB) {
    msActor* a = msActorFromPid(pidA);
    if (a != NULL) {
        msActorRemoveLink(a, pidB);
        msHazardClear(a);
    }
    msActor* b = msActorFromPid(pidB);
    if (b != NULL) {
        msActorRemoveLink(b, pidA);
        msHazardClear(b);
    }
}

/* Set trap_exits flag (Erlang: process_flag(trap_exit, true)). */
static inline void msActorTrapExits(int64_t pid, bool trap) {
    msActor* a = msActorFromPid(pid);
    if (a == NULL) return;
    a->trapExits = trap;
    msHazardClear(a);
}

/* ===== Idle Timeout (Erlang: gen_server timeout) ===== */

/* Set idle timeout: onIdle fires after ms of no messages. 0 = disable. */
static inline void msActorSetIdleTimeout(int64_t pid, double ms) {
    msActor* a = msActorFromPid(pid);
    if (a == NULL) return;
    int64_t prev = a->idleTimeoutMs;
    a->idleTimeoutMs = (int64_t)ms;
    if (ms > 0) {
        a->lastActivityMs = msMonoTimeMs();
        if (prev == 0) atomic_fetch_add(&msActorsWithTimeout, 1);
        /* Cap event loop sleep so idle scan fires on time (use smallest timeout) */
        msSetActorIdleCap((int)ms);
    } else {
        if (prev > 0) {
            int remaining = atomic_fetch_sub(&msActorsWithTimeout, 1) - 1;
            if (remaining <= 0) msSetActorIdleCap(0);  /* no more timeouts — remove cap */
        }
    }
    msHazardClear(a);
}

/* ===== Monitors (unidirectional DOWN messages, Erlang parity) ===== */

/* Global monotonic monitor reference counter (Erlang: make_ref()) */
extern _Atomic(int64_t) msNextMonitorRef;

/* Monitor a target actor. Returns a unique monitor reference (Erlang: erlang:monitor/2).
 * When target dies, watcher receives DOWN message with this ref + target pid + reason. */
static inline int64_t msActorMonitorPid(int64_t watcherPid, int64_t targetPid) {
    msActor* target = msActorFromPid(targetPid);
    if (target == NULL) return 0;
    msActor* watcher = msActorFromPid(watcherPid);
    if (watcher == NULL) { msHazardClear(target); return 0; }
    msHazardClear(watcher);  /* existence check only — the list stores the pid */
    int64_t ref = atomic_fetch_add(&msNextMonitorRef, 1);
    /* Add watcher pid to target's monitor list */
    if (target->monitorCount >= target->monitorCap) {
        int newCap = target->monitorCap == 0 ? 4 : target->monitorCap * 2;
        target->monitorWatchers = (int64_t*)realloc(target->monitorWatchers, newCap * sizeof(int64_t));
        target->monitorRefs = (int64_t*)realloc(target->monitorRefs, newCap * sizeof(int64_t));
        target->monitorCap = newCap;
    }
    target->monitorWatchers[target->monitorCount] = watcherPid;
    target->monitorRefs[target->monitorCount] = ref;
    target->monitorCount++;
    msHazardClear(target);
    return ref;
}

/* Remove a monitor by reference. */
static inline void msActorDemonitorPid(int64_t targetPid, int64_t ref) {
    msActor* target = msActorFromPid(targetPid);
    if (target == NULL) return;
    for (int i = 0; i < target->monitorCount; i++) {
        if (target->monitorRefs[i] == ref) {
            target->monitorWatchers[i] = target->monitorWatchers[target->monitorCount - 1];
            target->monitorRefs[i] = target->monitorRefs[target->monitorCount - 1];
            target->monitorCount--;
            msHazardClear(target);
            return;
        }
    }
    msHazardClear(target);
}

/* ===== Name Registry (Erlang: register/2, whereis/1, unregister/1) =====
 *
 * Global string→actor hash table. Open addressing, linear probing, DJB2 hash.
 * Mutex-protected (registry ops are rare — startup/shutdown only).
 * 1:1 constraint: one name per pid, one pid per name (Erlang parity).
 * Auto-unregister on actor death (msActorDestroyWithReason).
 */

/* Remove entry at slot and rehash subsequent probe chain entries. Must hold lock. */
static inline void msNameRegistryRemoveSlot(uint32_t slot) {
    msStringDestroy(msNameRegistry[slot].name);
    msNameRegistry[slot].name = MS_EMPTY_STRING;
    msNameRegistry[slot].pid = 0;
    msNameRegistryCount--;
    uint32_t j = (slot + 1) & (msNameRegistryCap - 1);
    for (uint32_t guard = 0; guard < (uint32_t)msNameRegistryCap && msNameRegistry[j].pid != 0; guard++) {
        msNameEntry displaced = msNameRegistry[j];
        msNameRegistry[j].pid = 0;
        msNameRegistry[j].name = MS_EMPTY_STRING;
        msNameRegistryCount--;
        uint32_t h = (uint32_t)msStringHash(displaced.name) & (msNameRegistryCap - 1);
        for (uint32_t k = 0; k < (uint32_t)msNameRegistryCap; k++) {
            uint32_t s = (h + k) & (msNameRegistryCap - 1);
            if (msNameRegistry[s].pid == 0) {
                msNameRegistry[s] = displaced;
                msNameRegistryCount++;
                break;
            }
        }
        j = (j + 1) & (msNameRegistryCap - 1);
    }
}

/* Register name → pid. Returns 1.0 (true) on success, 0.0 if name taken or pid already named. */
static inline double msActorRegisterName(int64_t pid, msString name) {
    msActor* a = msActorFromPid(pid);
    if (a == NULL || name.len == 0) {
        if (a != NULL) msHazardClear(a);
        return 0.0;
    }
    /* Existence check only — the registry stores the pid. If the actor dies
     * between this check and insert, the entry is stale-but-benign (whereis
     * returns a dead pid, FromPid → NULL). */
    msHazardClear(a);
    pthread_mutex_lock(&msNameRegistryLock);
    msNameRegistryEnsure();
    /* 1:1 constraint: scan all occupied slots */
    for (int i = 0; i < msNameRegistryCap; i++) {
        if (msNameRegistry[i].pid == 0) continue;
        if (msStringEquals(msNameRegistry[i].name, name)) {
            pthread_mutex_unlock(&msNameRegistryLock);
            return 0.0;  /* name already taken */
        }
        if (msNameRegistry[i].pid == pid) {
            pthread_mutex_unlock(&msNameRegistryLock);
            return 0.0;  /* pid already has a name */
        }
    }
    /* Grow if load factor exceeds 75% */
    if (msNameRegistryCount >= msNameRegistryCap * 3 / 4) {
        msNameRegistryGrow();
    }
    /* Insert at probed slot */
    uint32_t h = (uint32_t)msStringHash(name) & (msNameRegistryCap - 1);
    for (int i = 0; i < msNameRegistryCap; i++) {
        uint32_t s = (h + i) & (msNameRegistryCap - 1);
        if (msNameRegistry[s].pid == 0) {
            msNameRegistry[s].name = msStringNew(name.p->data, name.len);
            msNameRegistry[s].pid = pid;
            msNameRegistryCount++;
            pthread_mutex_unlock(&msNameRegistryLock);
            return 1.0;
        }
    }
    pthread_mutex_unlock(&msNameRegistryLock);
    return 0.0;
}

/* Look up pid by name. Returns pid (int64) or 0 if not found. */
static inline int64_t msActorWhereis(msString name) {
    if (name.len == 0 || msNameRegistry == NULL) return 0;
    pthread_mutex_lock(&msNameRegistryLock);
    uint32_t h = (uint32_t)msStringHash(name) & (msNameRegistryCap - 1);
    for (int i = 0; i < msNameRegistryCap; i++) {
        uint32_t s = (h + i) & (msNameRegistryCap - 1);
        if (msNameRegistry[s].pid == 0) break;
        if (msStringEquals(msNameRegistry[s].name, name)) {
            int64_t pid = msNameRegistry[s].pid;
            pthread_mutex_unlock(&msNameRegistryLock);
            return pid;
        }
    }
    pthread_mutex_unlock(&msNameRegistryLock);
    return 0;
}

/* Unregister a name. No-op if not registered. */
static inline void msActorUnregisterName(msString name) {
    if (name.len == 0 || msNameRegistry == NULL) return;
    pthread_mutex_lock(&msNameRegistryLock);
    uint32_t h = (uint32_t)msStringHash(name) & (msNameRegistryCap - 1);
    for (int i = 0; i < msNameRegistryCap; i++) {
        uint32_t s = (h + i) & (msNameRegistryCap - 1);
        if (msNameRegistry[s].pid == 0) break;
        if (msStringEquals(msNameRegistry[s].name, name)) {
            msNameRegistryRemoveSlot(s);
            pthread_mutex_unlock(&msNameRegistryLock);
            return;
        }
    }
    pthread_mutex_unlock(&msNameRegistryLock);
}

/* Initialize name registry — sets the destroy hook so auto-unregister works cross-TU.
 * The hook is stored in dispatch.c (shared across all TUs). When any TU's
 * msActorDestroyWithReason calls msCallActorDestroyHook, it calls back into THIS TU's
 * msActorUnregisterByPtr (which accesses this TU's msNameRegistry). */
static inline void msActorNameRegistryInitHook(msActor* a) {
    if (msNameRegistryCount > 0) msActorUnregisterByPtr(a);
}
static inline void msActorNameRegistryInit(void) {
    msSetActorDestroyHook((void (*)(void*))msActorNameRegistryInitHook);
}

/* Unregister by actor pointer (auto-cleanup on actor death). */
static inline void msActorUnregisterByPtr(msActor* a) {
    if (msNameRegistry == NULL) return;
    pthread_mutex_lock(&msNameRegistryLock);
    for (int i = 0; i < msNameRegistryCap; i++) {
        if (msNameRegistry[i].pid == a->pid) {
            msNameRegistryRemoveSlot(i);
            pthread_mutex_unlock(&msNameRegistryLock);
            return;
        }
    }
    pthread_mutex_unlock(&msNameRegistryLock);
}

/* ===== Multi-Scheduler Actor Registry (Phase 5: Parallel Actors) =====
 *
 * Actors are round-robin assigned to schedulers (threads).
 * Scheduler 0 = main thread (also runs msRunOnce for I/O).
 * Schedulers 1..N-1 = spawn pool worker threads.
 * Run queues: lock-free stack per scheduler — O(1) push/pop, scales to 10K+ actors.
 * Work stealing: idle workers pop from other schedulers' run queues — O(schedulers).
 */

extern _Atomic(int) msNextActorRR;        /* round-robin assignment counter */

/* Forward declarations */
extern void msSetActorPollHook(bool (*hook)(void));  /* dispatch.c */
extern void msPoolSetActorHooks(bool (*pollFn)(void), void (*idSetterFn)(int));  /* pool.c */
static inline bool msActorPollLocal(void);            /* defined below */

#include "runtime/promise/pool.h"

/* Grow a scheduler's actor registry. Old array is retained (not freed) because
 * concurrent CD readers on other threads may still be traversing it.
 * Bounded cost: total retained memory ≈ current array size. */
static inline void msSchedActorsGrow(msSchedActors* sched, int needed) {
    int newCap = sched->cap == 0 ? MS_SCHED_INIT_CAP : sched->cap * 2;
    while (newCap < needed) newCap *= 2;
    msActor** newArr = (msActor**)calloc(newCap, sizeof(msActor*));
    if (sched->actors != NULL) {
        memcpy(newArr, sched->actors, sched->cap * sizeof(msActor*));
        /* Old array intentionally NOT freed — CD may be reading it concurrently.
         * The count acquire/release pair ensures CD sees consistent entries. */
    }
    sched->actors = newArr;
    sched->cap = newCap;
}

/* Scheduler ID setter — called by pool workers via hook to set their TLS scheduler ID */
static inline void msSetSchedulerID(int id) {
    msMySchedulerID = id;
}

static inline void msActorRegister(msActor* a) {
    if (msSchedulerCount == 0) {
        /* Hooks MUST be set before msPoolGet(): pool workers spawn inside
         * msPoolInit and read msPoolSchedIdSetterFn at startup. Hook-after-pool
         * races leave worker TLS at -1 → msActorPollLocal early-returns →
         * only main thread polls actors. */
        msEnsureWakePipe();  /* wake pipe must exist before any actor send */
        msMySchedulerID = 0;  /* main thread = scheduler 0 */
        msSetActorPollHook(msActorPollLocal);
        msPoolSetActorHooks(msActorPollLocal, msSetSchedulerID);
        msThreadPool* p = msPoolGet();
        msSchedulerCount = (p != NULL ? p->workerCount : 0) + 1;
        if (msSchedulerCount > MS_MAX_SCHEDULERS) msSchedulerCount = MS_MAX_SCHEDULERS;
        /* Create async cycle detector actor on scheduler 0 */
        msCDInit();
    }
    /* Assignment: parent's sched → creator-thread's sched → RR fallback.
     * Pony-parity locality. Cross-thread IO completions (#88/#89) aren't wired
     * yet, so an actor accepted on thread A but running on B silently hangs
     * on recvAsync — pinning to creator avoids that until IO wake is plumbed. */
    int id;
    if (msCurrentActor != NULL) {
        id = msCurrentActor->schedulerID;
    } else if (msMySchedulerID >= 0 && msMySchedulerID < msSchedulerCount) {
        id = msMySchedulerID;
    } else {
        id = atomic_fetch_add(&msNextActorRR, 1) % msSchedulerCount;
    }
    a->schedulerID = id;
    msSchedActors* sched = &msSchedulers[id];
    int cnt = atomic_load_explicit(&sched->count, memory_order_acquire);
    if (cnt >= sched->cap) {
        msSchedActorsGrow(sched, cnt + 1);
    }
    sched->actors[cnt] = a;
    atomic_store_explicit(&sched->count, cnt + 1, memory_order_release);
    msHazardClear(a);
}

/*
 * Poll actors on THIS scheduler thread only.
 * Called from: main thread (via msRunOnce hook) and pool workers (after spawn tasks).
 */
static inline bool msActorPollLocal(void) {
    int id = msMySchedulerID;
    if (id < 0 || id >= msSchedulerCount) return false;
    bool didWork = false;

    /* Phase 1: Drain own run queue — O(1) per actor, only actors with work.
     * Pony parity: pop from queue, not scan array. Scales to 10K+ actors. */
    msSchedActors* sched = &msSchedulers[id];
    msActor* a;
    while ((a = msSchedRunPop(sched)) != NULL) {
        if (msActorHasFlag(a, MS_ACTOR_MUTED)) continue;
        int n = msActorProcess(a, MS_ACTOR_BATCH);
        if (n > 0) didWork = true;
    }
    /* Clear the amortized-wake flag AFTER fully draining — the next sender
     * must re-wake us if more work arrives. Placed here (not later) so a
     * subsequent send between clear and sleep still triggers a wake syscall. */
    if (!didWork) {
        atomic_store_explicit(&sched->wakeAmortized, false, memory_order_release);
    }

    /* Phase 2: Work stealing — if idle, pop from other schedulers' run queues.
     * O(schedulers) not O(actors). CAS guard prevents double-processing. */
    if (!didWork) {
        for (int s = 0; s < msSchedulerCount; s++) {
            if (s == id) continue;
            msSchedActors* other = &msSchedulers[s];
            a = msSchedRunPop(other);
            if (a != NULL) {
                if (!msActorHasFlag(a, MS_ACTOR_MUTED)) {
                    int n = msActorProcess(a, MS_ACTOR_BATCH);
                    if (n > 0) didWork = true;
                }
                break;  /* stole one actor, return to own work */
            }
        }
    }

    /* Cycle detection: scheduler 0 sends periodic TICK to CD actor (async).
     * Interval scales with actor count: 100 base + 1 per 10 actors.
     * 10 actors→101, 1K→200, 10K→1100, 1M→100100 polls between ticks. */
    if (id == 0) {
        sched->pollCount++;
        int actorEstimate = atomic_load_explicit(&sched->count, memory_order_relaxed) * msSchedulerCount;
        int cdInterval = 100 + actorEstimate / 10;
        if (sched->pollCount >= cdInterval) {
            sched->pollCount = 0;
            msCDTick();
        }
    }

    /* Phase 3: Idle timeout — scan actors with timeouts on this scheduler.
     * Skipped entirely when no actors have timeouts (zero overhead). */
    if (atomic_load_explicit(&msActorsWithTimeout, memory_order_relaxed) > 0) {
        int64_t now = msMonoTimeMs();
        int cnt = atomic_load_explicit(&sched->count, memory_order_acquire);
        for (int i = 0; i < cnt; i++) {
            msActor* ta = sched->actors[i];
            if (ta->idleTimeoutMs > 0 && ta->lastActivityMs > 0 &&
                atomic_load_explicit(&ta->alive, memory_order_relaxed) &&
                !atomic_load_explicit(&ta->hasWork, memory_order_relaxed) &&
                (now - ta->lastActivityMs) >= ta->idleTimeoutMs) {
                msMessage* idleMsg = msMsgAllocSized(-3, NULL, 0);
                msActorSend(ta, idleMsg);
                ta->lastActivityMs = now;  /* re-arm for repeated firing */
            }
        }
    }

    /* Phase 4: I18 reap scan — collects stop-flagged actors no visit will reach:
     * the suspended-then-stopped lane (suspended actors are never mailbox-
     * scheduled; the resume callback only opens the gate) and any visit that
     * raced the flag. Owner thread only — registry writes and free stay
     * single-threaded per scheduler. */
    if (atomic_load_explicit(&msActorsStopPending, memory_order_acquire) > 0) {
        int cnt = atomic_load_explicit(&sched->count, memory_order_acquire);
        for (int i = 0; i < cnt; i++) {
            msActor* sa = sched->actors[i];
            if (!atomic_load_explicit(&sa->stopRequested, memory_order_acquire)) continue;
            /* Suspended-stopped lane ONLY. The latched SUSPENDED flag keeps
             * senders off the wasEmpty edge, so no run-queue entry can exist —
             * `scheduled` alone can't prove that (markEmpty/push overwrite race
             * frees a live queue node → pop UAF). Awake/idle stops always get a
             * STOP-msg visit whose gate reaps with the pop owned. */
            if (!msActorHasFlag(sa, MS_ACTOR_SUSPENDED)) continue;
            if (atomic_load_explicit(&sa->suspendedFut, memory_order_acquire) != NULL) continue;
            bool expP = false;
            if (!atomic_compare_exchange_strong_explicit(&sa->processing, &expP, true,
                    memory_order_acquire, memory_order_relaxed)) continue;
            if (atomic_load_explicit(&sa->scheduled, memory_order_acquire)) {
                /* Queued — that visit's gate reaps; don't double-own. */
                atomic_store_explicit(&sa->processing, false, memory_order_release);
                continue;
            }
            msActorDestroyWithReason(sa,
                atomic_load_explicit(&sa->stopReason, memory_order_relaxed));
            didWork = true;
            cnt = atomic_load_explicit(&sched->count, memory_order_acquire);
            i--;  /* swap-remove put a new actor in slot i — re-examine */
        }
    }

    /* I19: drain deferred frees — shells whose hazard pins cleared since the
     * last poll. Owner thread only; the pid slot is long released, so the
     * list can only shrink. */
    if (sched->deferredFree != NULL) {
        msActor* d = sched->deferredFree;
        sched->deferredFree = NULL;
        while (d != NULL) {
            msActor* nx = atomic_load_explicit(&d->runNext, memory_order_relaxed);
            if (msHazardScan(d)) {
                atomic_store_explicit(&d->runNext, sched->deferredFree, memory_order_relaxed);
                sched->deferredFree = d;
            } else {
                free(d);
                didWork = true;
            }
            d = nx;
        }
    }

    return didWork;
}

/* Exit-poll: drain ALL run queues + scan ALL registries (belt-and-suspenders).
 * Called at program exit to flush remaining messages. */
static inline bool msActorPollAll(void) {
    bool didWork = false;
    /* Drain run queues first */
    for (int s = 0; s < msSchedulerCount; s++) {
        msActor* a;
        while ((a = msSchedRunPop(&msSchedulers[s])) != NULL) {
            if (!msActorHasFlag(a, MS_ACTOR_MUTED)) {
                int n = msActorProcess(a, MS_ACTOR_BATCH);
                if (n > 0) didWork = true;
            }
        }
    }
    /* Scan registry for stragglers not in run queue */
    for (int s = 0; s < msSchedulerCount; s++) {
        msSchedActors* sched = &msSchedulers[s];
        int cnt2 = atomic_load_explicit(&sched->count, memory_order_acquire);
        for (int i = 0; i < cnt2; i++) {
            msActor* a = sched->actors[i];
            if (msActorHasFlag(a, MS_ACTOR_MUTED)) continue;
            if (atomic_load_explicit(&a->hasWork, memory_order_acquire)) {
                int n = msActorProcess(a, MS_ACTOR_BATCH);
                if (n > 0) didWork = true;
            }
        }
    }
    return didWork;
}

/* Quiescence detection: true when ALL actors across ALL schedulers are idle. */
static inline bool msActorSystemQuiescent(void) {
    for (int s = 0; s < msSchedulerCount; s++) {
        msSchedActors* sched = &msSchedulers[s];
        int cnt = atomic_load_explicit(&sched->count, memory_order_acquire);
        for (int i = 0; i < cnt; i++) {
            msActor* a = sched->actors[i];
            if (atomic_load_explicit(&a->hasWork, memory_order_acquire)) return false;
            if (atomic_load_explicit(&a->processing, memory_order_acquire)) return false;
        }
    }
    return true;
}

/* ===== Async Cycle Detector Actor (Pony ORCA parity) =====
 *
 * The CD is a system actor on scheduler 0. It receives periodic TICK messages
 * from msActorPollLocal, scans BLOCKED flags across all schedulers, and
 * detects dead reference cycles. Non-blocking — runs as a normal actor batch.
 *
 * Protocol:
 *   1. msActorProcess sets BLOCKED flag when actor becomes idle (RC > 0)
 *   2. msActorProcess clears BLOCKED flag when actor gets new work
 *   3. msActorPollLocal (scheduler 0) sends TICK to CD at dynamic intervals (scales with actor count)
 *   4. CD dispatch: reverse-reachability scan (mark blocked, unmark live-reachable)
 *   5. Unreachable blocked actors = dead cycles → destroy with link/monitor propagation
 */

#define MS_CD_MSG_TICK 0

/* Scan all schedulers for dead cycles using reverse reachability.
 *
 * Algorithm (3 passes):
 *   Pass 1: Mark all BLOCKED actors as CYCLE_MARKED (candidates).
 *   Pass 2: For each LIVE (non-BLOCKED) actor, trace refs and UNMARK
 *           any BLOCKED actors reachable from it (they're kept alive).
 *   Pass 3: Remaining CYCLE_MARKED actors are unreachable from any live
 *           actor → dead cycle → collect.
 *
 * This catches cycles where a member has refs outside the cycle (e.g.,
 * A→B→A where A also refs live D — old algorithm missed this). */
static inline void msCDUnmarkReachable(msActor* a) {
    /* Iterative pid-walk: one child pinned at a time (recursion would pin per
     * depth and overflow the hazard slots). Reaped referents skip cleanly. */
    int cap = 64, top = 0;
    int64_t* stack = (int64_t*)malloc(cap * sizeof(int64_t));
    for (int r = 0; r < a->refsCount; r++) {
        if (top >= cap) { cap *= 2; stack = (int64_t*)realloc(stack, cap * sizeof(int64_t)); }
        stack[top++] = a->refs[r];
    }
    while (top > 0) {
        msActor* ref = msActorFromPid(stack[--top]);
        if (ref == NULL) continue;
        if (msActorHasFlag(ref, MS_ACTOR_CYCLE_MARKED)) {
            msActorClearFlag(ref, MS_ACTOR_CYCLE_MARKED);
            for (int r = 0; r < ref->refsCount; r++) {
                if (top >= cap) { cap *= 2; stack = (int64_t*)realloc(stack, cap * sizeof(int64_t)); }
                stack[top++] = ref->refs[r];
            }
        }
        msHazardClear(ref);
    }
    free(stack);
}

static inline void msCDRunDetection(void) {
    /* I19: iterate the pid table, not per-sched registries — other owners reap
     * concurrently, and a pinned slot is the only safe cross-scheduler view. */
    int32_t slots = atomic_load_explicit(&msPidNextSlot, memory_order_acquire);
    /* Pass 1: mark all BLOCKED actors with refs as candidates */
    for (int32_t i = 0; i < slots; i++) {
        msActor* a = msPidPinSlot(i);
        if (a == NULL) continue;
        if (msActorHasFlag(a, MS_ACTOR_BLOCKED) && a->refsCount > 0) {
            msActorSetFlag(a, MS_ACTOR_CYCLE_MARKED);
        }
        msHazardClear(a);
    }
    /* Pass 2: unmark actors reachable from any LIVE actor */
    for (int32_t i = 0; i < slots; i++) {
        msActor* a = msPidPinSlot(i);
        if (a == NULL) continue;
        if (!msActorHasFlag(a, MS_ACTOR_BLOCKED)) {
            msCDUnmarkReachable(a);
        }
        msHazardClear(a);
    }
    /* Pass 3: collect remaining marked actors — dead cycles */
    for (int32_t i = 0; i < slots; i++) {
        msActor* a = msPidPinSlot(i);
        if (a == NULL) continue;
        if (msActorHasFlag(a, MS_ACTOR_CYCLE_MARKED)) {
            msActorClearFlag(a, MS_ACTOR_CYCLE_MARKED);
            int64_t deadPid = a->pid;
            msHazardClear(a);
            msActorStop(deadPid, MS_EXIT_NORMAL);
        } else {
            msHazardClear(a);
        }
    }
}

/* CD actor dispatch — receives TICK messages, runs detection */
static inline void msCDDispatch(void* state, void* msg) {
    (void)state; (void)msg;
    msCDRunDetection();
}

/* The global CD actor — created during scheduler init */
extern msActor* msCycleDetectorActor;

static inline void msCDInit(void) {
    if (msCycleDetectorActor != NULL) return;
    msCycleDetectorActor = msActorCreate(NULL, msCDDispatch);
    msCycleDetectorActor->schedulerID = 0;
    msSchedActors* sched = &msSchedulers[0];
    int cnt = atomic_load_explicit(&sched->count, memory_order_acquire);
    if (cnt >= sched->cap) {
        msSchedActorsGrow(sched, cnt + 1);
    }
    sched->actors[cnt] = msCycleDetectorActor;
    atomic_store_explicit(&sched->count, cnt + 1, memory_order_release);
}

/* Send TICK to CD actor (called from msActorPollLocal on scheduler 0) */
static inline void msCDTick(void) {
    if (msCycleDetectorActor == NULL) return;
    msMessage* msg = msMsgAlloc(MS_CD_MSG_TICK, NULL);
    msActorSend(msCycleDetectorActor, msg);
}

#endif /* MS_ACTOR_H */
