/*
 * MetaScript Actor Runtime
 *
 * Actor = state struct + MPSC mailbox + dispatch function.
 * Scheduler polls actor mailboxes directly (no syscall, no pipe).
 * Scheduler 0 also runs msRunOnce() for I/O + timers + spawn.
 *
 * Lifecycle: msActorCreate → msActorSend/msActorCall → msActorProcess → msActorDestroy
 */

#ifndef MS_ACTOR_H
#define MS_ACTOR_H

#include "mailbox.h"
#include "runtime/drc.h"
#include <stdint.h>
#include <stdbool.h>

/* ===== Actor Dispatch Function ===== */

/* Dispatch receives state + full message (void* → msMessage*).
 * Dispatch accesses msg->kind for routing and msg->replyFuture for call-semantics. */
typedef void (*msActorDispatchFn)(void* state, void* msg);

/* ===== Sync Flags (Pony-derived) ===== */

#define MS_ACTOR_OVERLOADED     0x01  /* mailbox non-empty after batch */
#define MS_ACTOR_UNDER_PRESSURE 0x02  /* application-level backpressure */
#define MS_ACTOR_MUTED          0x04  /* paused by scheduler (target overloaded) */
#define MS_ACTOR_BLOCKED        0x08  /* idle + RC > 0 (cycle detection candidate) */
#define MS_ACTOR_CYCLE_MARKED   0x10  /* internal: marked for cycle collection (do not reuse MUTED) */

/* ===== Actor Struct ===== */

typedef struct msActor {
    msMpscQueue mailbox;          /* Lock-free MPSC message queue */
    msActorDispatchFn dispatch;   /* Message handler (generated by compiler) */
    void* state;                  /* Pointer to actor's data struct (Ref<T>) */
    int32_t schedulerID;          /* Pinned scheduler index */
    _Atomic(uint8_t) syncFlags;   /* Backpressure + lifecycle flags */
    _Atomic(bool) hasWork;        /* Set on push, cleared after drain */
    /* Muting: actors paused because this actor is overloaded (dynamic, malloc on first use) */
    struct msActor** mutedBy;
    int mutedByCount;
    int mutedByCap;
    /* Cycle detection: actors this actor references (dynamic, malloc on first use) */
    struct msActor** refs;
    int refsCount;
    int refsCap;
} msActor;

/* ===== Batch Size ===== */

#define MS_ACTOR_BATCH 64
#define MS_CYCLE_INTERVAL 100  /* run cycle detector every N polls */

/* ===== Thread-local: currently executing actor (NULL if non-actor code) ===== */

#ifndef MS_THREAD_LOCAL
#ifdef _WIN32
#define MS_THREAD_LOCAL __declspec(thread)
#else
#define MS_THREAD_LOCAL _Thread_local
#endif
#endif

static MS_THREAD_LOCAL msActor* msCurrentActor = NULL;

/* ===== Flag Helpers ===== */

static inline uint8_t msActorGetFlags(msActor* a) {
    return atomic_load_explicit(&a->syncFlags, memory_order_acquire);
}

static inline void msActorSetFlag(msActor* a, uint8_t flag) {
    atomic_fetch_or_explicit(&a->syncFlags, flag, memory_order_release);
}

static inline void msActorClearFlag(msActor* a, uint8_t flag) {
    atomic_fetch_and_explicit(&a->syncFlags, (uint8_t)~flag, memory_order_release);
}

static inline bool msActorHasFlag(msActor* a, uint8_t flag) {
    return (msActorGetFlags(a) & flag) != 0;
}

/* ===== Muting ===== */

/* Mute a sender because the receiver is overloaded. */
static inline void msActorMute(msActor* sender, msActor* receiver) {
    if (sender == NULL || sender == receiver) return;
    if (msActorHasFlag(sender, MS_ACTOR_MUTED)) return;
    msActorSetFlag(sender, MS_ACTOR_MUTED);
    /* Track who we muted so we can unmute them later (grow on demand) */
    if (receiver->mutedByCount >= receiver->mutedByCap) {
        int newCap = receiver->mutedByCap == 0 ? 4 : receiver->mutedByCap * 2;
        receiver->mutedBy = (msActor**)realloc(receiver->mutedBy, newCap * sizeof(msActor*));
        receiver->mutedByCap = newCap;
    }
    receiver->mutedBy[receiver->mutedByCount++] = sender;
}

/* Unmute all actors that were muted because this actor was overloaded. */
static inline void msActorUnmuteAll(msActor* receiver) {
    for (int i = 0; i < receiver->mutedByCount; i++) {
        msActorClearFlag(receiver->mutedBy[i], MS_ACTOR_MUTED);
        receiver->mutedBy[i] = NULL;
    }
    receiver->mutedByCount = 0;
}

/* ===== Actor Lifecycle ===== */

static inline msActor* msActorCreate(void* state, msActorDispatchFn dispatch) {
    msActor* a = (msActor*)calloc(1, sizeof(msActor));
    msMpscInit(&a->mailbox);
    a->dispatch = dispatch;
    a->state = state;
    a->schedulerID = 0;
    atomic_store_explicit(&a->syncFlags, 0, memory_order_relaxed);
    atomic_store_explicit(&a->hasWork, false, memory_order_relaxed);
    a->mutedBy = NULL;
    a->mutedByCount = 0;
    a->mutedByCap = 0;
    a->refs = NULL;
    a->refsCount = 0;
    a->refsCap = 0;
    return a;
}

/*
 * Send a message to an actor (any thread, wait-free).
 * If receiver is overloaded, mutes the current actor (sender).
 */
static inline void msActorSend(msActor* a, msMessage* msg) {
    bool wasEmpty = msMpscPush(&a->mailbox, msg);
    atomic_store_explicit(&a->hasWork, true, memory_order_release);

    /* Backpressure: if receiver overloaded, mute sender */
    if (msActorHasFlag(a, MS_ACTOR_OVERLOADED) && msCurrentActor != NULL) {
        msActorMute(msCurrentActor, a);
    }

    if (wasEmpty) {
        /* Phase 5+: wake scheduler via condvar/futex here */
    }
}

/*
 * Process up to `maxBatch` messages from the actor's mailbox.
 * Sets/clears OVERLOADED flag. Triggers unmute when caught up.
 */
static inline int msActorProcess(msActor* a, int maxBatch) {
    msActor* prevActor = msCurrentActor;
    msCurrentActor = a;

    /* Clear BLOCKED — we're actively processing */
    msActorClearFlag(a, MS_ACTOR_BLOCKED);

    int processed = 0;
    while (processed < maxBatch) {
        msMessage* msg = msMpscPop(&a->mailbox);
        if (msg == NULL) break;
        a->dispatch(a->state, (void*)msg);
        /* Don't free msg here — MPSC pop made it the new tail stub.
         * It gets freed on the NEXT pop when a newer message takes its place. */
        processed++;
    }

    /* Check mailbox state after batch */
    if (msMpscIsEmpty(&a->mailbox)) {
        if (msMpscMarkEmpty(&a->mailbox)) {
            atomic_store_explicit(&a->hasWork, false, memory_order_release);
        }
        /* Caught up: clear overload + unmute senders */
        if (msActorHasFlag(a, MS_ACTOR_OVERLOADED)) {
            msActorClearFlag(a, MS_ACTOR_OVERLOADED);
            msActorUnmuteAll(a);
        }
        /* Idle with RC > 0: candidate for cycle detection */
        if (a->state != NULL) {
            msRefHeader* h = msHeader(a->state);
            if (h->rc > 0) {
                msActorSetFlag(a, MS_ACTOR_BLOCKED);
            }
        }
    } else {
        /* Still has messages after batch: mark overloaded */
        msActorSetFlag(a, MS_ACTOR_OVERLOADED);
    }

    msCurrentActor = prevActor;
    return processed;
}

/* ===== Message Accessors (for dispatch functions generated by compiler) ===== */

static inline int32_t msMsgKind(void* msg) {
    return ((msMessage*)msg)->kind;
}

static inline void* msMsgReplyFuture(void* msg) {
    return ((msMessage*)msg)->replyFuture;
}

/* Future completion helpers — thin wrappers so dispatch can complete reply futures.
 * These call into future.h APIs. Include future.h before actor.h for call-semantics. */
static inline void msMsgCompleteDouble(void* fut, double val) {
    if (fut == NULL) return;
    /* Cast to msFuture_double* and complete. Requires future.h to be included. */
    typedef struct { bool finished; bool failed; bool cancelled; bool isBoxed; void* error; void (*vd)(void*); void* cb; void* cbTail; double value; } msFutSimpleDouble;
    msFutSimpleDouble* f = (msFutSimpleDouble*)fut;
    f->value = val;
    f->finished = true;
}

static inline void msMsgCompleteVoid(void* fut) {
    if (fut == NULL) return;
    typedef struct { bool finished; } msFutSimpleVoid;
    msFutSimpleVoid* f = (msFutSimpleVoid*)fut;
    f->finished = true;
}

static inline void msActorDestroy(msActor* a) {
    /* Unmute anyone we caused to be muted */
    msActorUnmuteAll(a);
    /* Drain remaining messages */
    msMessage* msg;
    while ((msg = msMpscPop(&a->mailbox)) != NULL) {
        msMsgFree(msg);
    }
    msMpscDestroy(&a->mailbox);
    if (a->mutedBy != NULL) free(a->mutedBy);
    if (a->refs != NULL) free(a->refs);
    free(a);
}

/* ===== Actor References (for cycle detection) ===== */

static inline void msActorAddRef(msActor* from, msActor* to) {
    if (from == NULL || to == NULL || from == to) return;
    /* Check for duplicate */
    for (int i = 0; i < from->refsCount; i++) {
        if (from->refs[i] == to) return;
    }
    /* Grow on demand */
    if (from->refsCount >= from->refsCap) {
        int newCap = from->refsCap == 0 ? 4 : from->refsCap * 2;
        from->refs = (msActor**)realloc(from->refs, newCap * sizeof(msActor*));
        from->refsCap = newCap;
    }
    from->refs[from->refsCount++] = to;
}

/* ===== Scheduler (minimal, single-threaded for Phase 4) ===== */

#define MS_MAX_ACTORS 1024

typedef struct msActorRegistry {
    msActor* actors[MS_MAX_ACTORS];
    int count;
    int pollCount;  /* for periodic cycle detection */
} msActorRegistry;

static msActorRegistry msGlobalActors = { .count = 0, .pollCount = 0 };

static inline void msActorRegister(msActor* a) {
    if (msGlobalActors.count < MS_MAX_ACTORS) {
        msGlobalActors.actors[msGlobalActors.count++] = a;
    }
}

/*
 * Poll all registered actors. Skips muted actors.
 * Returns true if any work was done.
 */
static inline bool msActorPollAll(void) {
    bool didWork = false;
    for (int i = 0; i < msGlobalActors.count; i++) {
        msActor* a = msGlobalActors.actors[i];
        /* Skip muted actors (backpressure) */
        if (msActorHasFlag(a, MS_ACTOR_MUTED)) continue;
        if (atomic_load_explicit(&a->hasWork, memory_order_acquire)) {
            int n = msActorProcess(a, MS_ACTOR_BATCH);
            if (n > 0) didWork = true;
        }
    }
    /* Periodic cycle detection (every MS_CYCLE_INTERVAL polls) */
    msGlobalActors.pollCount++;
    if (msGlobalActors.pollCount >= MS_CYCLE_INTERVAL) {
        msGlobalActors.pollCount = 0;
        /* Cycle detection defined in cycle.h — include it to enable.
         * If not included, this is a no-op (weak symbol or ifdef). */
#ifdef MS_ACTOR_CYCLE_H
        msCycleDetectorRun();
#endif
    }

    return didWork;
}

#endif /* MS_ACTOR_H */
