/*
 * MetaScript Actor Runtime
 *
 * Actor = state struct + MPSC mailbox + dispatch function.
 * Scheduler polls actor mailboxes directly (no syscall, no pipe).
 * Scheduler 0 also runs msRunOnce() for I/O + timers + spawn.
 *
 * Lifecycle: msActorCreate → msActorSend/msActorCall → msActorProcess → msActorDestroy
 */

#ifndef MS_ACTOR_H
#define MS_ACTOR_H

#include "mailbox.h"
#include "arc.h"
#include <stdint.h>
#include <stdbool.h>

/* ===== Actor Dispatch Function ===== */

/* Called by scheduler for each message. `state` is the actor's data struct. */
typedef void (*msActorDispatchFn)(void* state, msMessage* msg);

/* ===== Sync Flags (Pony-derived, Phase 6 backpressure) ===== */

#define MS_ACTOR_OVERLOADED    0x01
#define MS_ACTOR_UNDER_PRESSURE 0x02
#define MS_ACTOR_MUTED         0x04

/* ===== Actor Struct ===== */

typedef struct msActor {
    msMpscQueue mailbox;          /* Lock-free MPSC message queue */
    msActorDispatchFn dispatch;   /* Message handler (generated by compiler) */
    void* state;                  /* Pointer to actor's data struct (Ref<T>) */
    int32_t schedulerID;          /* Pinned scheduler index */
    _Atomic(uint8_t) syncFlags;   /* Backpressure flags (Phase 6) */
    _Atomic(bool) hasWork;        /* Set on push, cleared after drain */
} msActor;

/* ===== Batch Size ===== */

#define MS_ACTOR_BATCH 64

/* ===== Actor Lifecycle ===== */

/*
 * Create an actor. Allocates actor struct, initializes mailbox.
 * `state` is the already-allocated data struct (from msAllocTyped).
 * `dispatch` is the compiler-generated message handler.
 * Returns the actor handle (for sending messages).
 */
static inline msActor* msActorCreate(void* state, msActorDispatchFn dispatch) {
    msActor* a = (msActor*)calloc(1, sizeof(msActor));
    msMpscInit(&a->mailbox);
    a->dispatch = dispatch;
    a->state = state;
    a->schedulerID = 0;  /* Pin to scheduler 0 for now (Phase 5: round-robin) */
    atomic_store_explicit(&a->syncFlags, 0, memory_order_relaxed);
    atomic_store_explicit(&a->hasWork, false, memory_order_relaxed);
    return a;
}

/*
 * Send a message to an actor (any thread, wait-free).
 * For void-return methods (send semantics): replyFuture is NULL.
 * For T-return methods (call semantics): replyFuture is a msFuture*.
 */
static inline void msActorSend(msActor* a, msMessage* msg) {
    bool wasEmpty = msMpscPush(&a->mailbox, msg);
    atomic_store_explicit(&a->hasWork, true, memory_order_release);
    if (wasEmpty) {
        /* Phase 5: wake scheduler via condvar/futex here */
    }
}

/*
 * Process up to `maxBatch` messages from the actor's mailbox.
 * Called by the scheduler on the actor's pinned thread.
 * Returns the number of messages processed.
 */
static inline int msActorProcess(msActor* a, int maxBatch) {
    int processed = 0;
    while (processed < maxBatch) {
        msMessage* msg = msMpscPop(&a->mailbox);
        if (msg == NULL) break;

        /* Dispatch to handler */
        a->dispatch(a->state, msg);

        /* Free message (args are value-copied into data[], no RC needed on msg itself) */
        msMsgFree(msg);
        processed++;
    }

    /* Check if more messages remain.
     * Only clear hasWork after successful markEmpty CAS.
     * If markEmpty fails (producer pushed between check and CAS), keep hasWork=true. */
    if (msMpscIsEmpty(&a->mailbox)) {
        if (msMpscMarkEmpty(&a->mailbox)) {
            atomic_store_explicit(&a->hasWork, false, memory_order_release);
        }
    }

    return processed;
}

/*
 * Destroy an actor. Drains remaining messages and frees the actor struct.
 * The actor's state struct is managed by DRC (Ref<T> with refcounting).
 */
static inline void msActorDestroy(msActor* a) {
    /* Drain remaining messages */
    msMessage* msg;
    while ((msg = msMpscPop(&a->mailbox)) != NULL) {
        /* TODO: destroy message args via DRC hooks if they hold RC references */
        msMsgFree(msg);
    }
    msMpscDestroy(&a->mailbox);
    /* Don't free a->state — DRC manages its lifetime via Ref<T> */
    free(a);
}

/* ===== Scheduler (minimal, single-threaded for Phase 4) ===== */

/* Global actor registry for scheduler polling.
 * Phase 5 replaces with per-scheduler actor lists. */

#define MS_MAX_ACTORS 1024

typedef struct msActorRegistry {
    msActor* actors[MS_MAX_ACTORS];
    int count;
} msActorRegistry;

static msActorRegistry msGlobalActors = { .count = 0 };

/* Register an actor for scheduler polling */
static inline void msActorRegister(msActor* a) {
    if (msGlobalActors.count < MS_MAX_ACTORS) {
        msGlobalActors.actors[msGlobalActors.count++] = a;
    }
}

/*
 * Poll all registered actors. Called from the main event loop.
 * Returns true if any work was done.
 */
static inline bool msActorPollAll(void) {
    bool didWork = false;
    for (int i = 0; i < msGlobalActors.count; i++) {
        msActor* a = msGlobalActors.actors[i];
        if (atomic_load_explicit(&a->hasWork, memory_order_acquire)) {
            int n = msActorProcess(a, MS_ACTOR_BATCH);
            if (n > 0) didWork = true;
        }
    }
    return didWork;
}

#endif /* MS_ACTOR_H */
