/*
 * MetaScript System Header — Master Include
 * This is the single header that generated C code includes.
 * It pulls in ARC, String, and Array runtimes.
 */
#ifndef SYSTEM_H
#define SYSTEM_H

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* ARC foundation (refcount, alloc, typeinfo) */
#include "std/runtime/arc.h"

/* ORC cycle collector (behind MS_ORC flag; no-op stubs otherwise) */
#include "std/runtime/orc.h"

/* String runtime (msString, all string ops) */
#include "std/core/string/native.h"

/* Array runtime (msNumberArray, msStringArray, msRefArray) */
#include "std/core/array/native.h"

/* Map runtime (msMap — string-keyed hash map) */
#include "std/core/map/native.h"

/* Buffer runtime (msBuffer — binary data, byte-oriented) */
#include "std/core/buffer/native.h"

/* ===== Type Aliases (C89 portability + codegen convenience) ===== */
typedef bool MS_BOOL;
#define MS_TRUE true
#define MS_FALSE false
#define MS_NIL NULL

/* ===== I/O ===== */

void msPrintln(msString s);

/* ===== DRC Lifecycle Stubs ===== */

/* Error flag — declared later (after MS_THREAD_LOCAL is defined by future.h) */

/* Closure function pointer types — with env (for lifted closures) */
typedef void (*msClosureFn)(void*, ...);
typedef double (*msClosureFnD)(void*, ...);
typedef MS_BOOL (*msClosureFnB)(void*, ...);
typedef msString (*msClosureFnS)(void*, ...);
typedef int32_t (*msClosureFnI)(void*, ...);
typedef int64_t (*msClosureFnI64)(void*, ...);
typedef void* (*msClosureFnP)(void*, ...);
/* Direct function pointer casts for named functions wrapped as closures:
   Standard reference pattern — per-call-site typed casts generated by closureCallLower.
   No generic typedefs needed; each call site gets its own typed cast like:
     ((MS_BOOL(*)(double))(pred.fn))(args)
   This avoids -Wdeprecated-non-prototype warnings from empty-paren typedefs. */
#ifndef MS_CLOSURE_DEFINED
#define MS_CLOSURE_DEFINED
typedef struct {
	msClosureFn fn;
	void* env;
} msClosure;
#endif

/* Async future runtime (msFuture, msFutureCreate/Complete/etc.) */
#include "std/core/promise/future.h"

/* Async dispatcher (event loop, msWaitFor, sleepAsync) */
#include "std/core/promise/dispatch.h"

/* Exception handling */
typedef struct {
	const char* message;
	int code;
} msException;

extern MS_THREAD_LOCAL bool msErr;
extern MS_THREAD_LOCAL msException* msCurrException;
void msClearException(void);
void msThrow(msString msg);

/* ===== DRC Lifecycle Macros ===== */
/* DRC passes args by value — macros access the variable directly for mutation. */

/* --- String lifecycle --- */
#define msStringDecref(s)     msStringDestroy(s)
#define msStringIncref(s)     do { \
	if ((s).p != NULL && !msIsLiteral(s)) { \
		msString __c = msStringNew((s).p->data, (s).len); \
		(s) = __c; \
	} \
} while(0)
/* =copy(var dest, src) — string copy-on-write assignment.
   Literal CoW: shallow copy for literals (pointer only, no alloc).
   Buffer reuse: if dest has enough capacity, memcpy without malloc.
   Full copy only when dest buffer is too small or is a literal. */
static inline void msStringCopy(msString* dest, msString src) {
	/* Identity: same pointer + same length = same string */
	if (dest->p == src.p && dest->len == src.len) return;
	/* Shared payload (e.g. after bitwise copy): both point to same buffer.
	   Don't free — source still owns it. Must allocate a fresh independent copy. */
	if (dest->p == src.p) {
		if (src.p != NULL && !msIsLiteral(src)) {
			*dest = msStringNew(src.p->data, src.len);
		} else {
			dest->len = src.len;  /* literal: just update length */
		}
		return;
	}
	/* Source is literal (or interned char): shallow copy — pointer only */
	if (msIsLiteral(src)) {
		if (!msIsLiteral(*dest)) free(dest->p);
		dest->len = src.len;
		dest->p = src.p;
		return;
	}
	/* Source is heap: try buffer reuse (reuse if capacity sufficient) */
	if (!msIsLiteral(*dest) && dest->p != NULL &&
		(dest->p->cap & MS_CAP_MASK) >= src.len) {
		dest->len = src.len;
		memcpy(dest->p->data, src.p->data, src.len + 1);
		return;
	}
	/* Must allocate new buffer */
	msString newStr = msStringNew(src.p->data, src.len);
	if (!msIsLiteral(*dest)) free(dest->p);
	*dest = newStr;
}
#define msStringWasMoved(s)   do { (s).len = 0; (s).p = NULL; } while(0)
#define msStringSink(d, s)    do { msStringDestroy(d); (d) = (s); } while(0)

/* --- Array lifecycle (unified) — uniquely owned payloads --- */
/* Reference parity: payloads are never shared. DRC emits deep copy or move. */
#define msArrayDestroy(arr)            do { if ((arr).p) { free((arr).p); } (arr).p = NULL; (arr).len = 0; } while(0)
#define msArrayWasMoved(arr)           do { (arr).len = 0; (arr).p = NULL; } while(0)
/* msArrayCopy: 1-arg = in-place copy marker (no-op for primitives), 2-arg = deep copy (allocate + memcpy) */
#define msArrayCopy1(arr)              /* primitive: bitwise copy handled by assignment */
#define msArrayCopy2(d, s)             do { \
	if ((s).p != NULL) { \
		size_t _ac_esz = sizeof((s).p->data[0]); \
		size_t _ac_sz = sizeof(msArrayPayloadBase) + (size_t)(s).p->cap * _ac_esz; \
		(d).p = (__typeof__((s).p))malloc(_ac_sz); \
		(d).p->cap = (s).p->cap; \
		memcpy((d).p->data, (s).p->data, (size_t)(s).len * _ac_esz); \
	} else { \
		(d).p = NULL; \
	} \
	(d).len = (s).len; \
} while(0)
#define msArrayCopy_GET(_1, _2, NAME, ...) NAME
#define msArrayCopy(...) msArrayCopy_GET(__VA_ARGS__, msArrayCopy2, msArrayCopy1)(__VA_ARGS__)
#define msArraySetLen(d, s)            msArraySetLenGeneric(&(d), (s).len, sizeof((s).p->data[0]))

/* --- Legacy aliases (used by classify.ms for DRC injection layer) --- */
#define msArrayNumberWasMoved(arr)     msArrayWasMoved(arr)
#define msArrayNumberSink(d, s)        do { msArrayDestroy(d); (d) = (s); } while(0)
#define msArrayStringDestroy(arr)      msStringArrayDestroy(&(arr))
/* Deep copy: allocate new payload, copy each string element */
#define msArrayStringCopy(d, s)        do { \
	int64_t _asc_len = (s).len; \
	msStringPayload* _asc_sp = (s).p; \
	msStringPayload* _asc_newp = NULL; \
	if (_asc_sp) { \
		size_t _asc_sz = sizeof(msStringPayload) + (size_t)_asc_sp->cap * sizeof(msString); \
		_asc_newp = (msStringPayload*)calloc(1, _asc_sz); \
		_asc_newp->cap = _asc_sp->cap; \
		for (int64_t _asc_i = 0; _asc_i < _asc_len; _asc_i++) { \
			_asc_newp->data[_asc_i] = _asc_sp->data[_asc_i]; \
			msStringIncref(_asc_newp->data[_asc_i]); \
		} \
	} \
	msStringArrayDestroy(&(d)); \
	(d).len = _asc_len; \
	(d).p = _asc_newp; \
} while(0)
#define msArrayStringWasMoved(arr)     msArrayWasMoved(arr)
#define msArrayStringSink(d, s)        do { msArrayDestroy(d); (d) = (s); } while(0)
#define msArrayRefDestroy(arr)         msRefArrayDestroy(&(arr))
/* Deep copy: allocate new payload, copy each ref element with incref */
#define msArrayRefCopy(d, s)           do { \
	int64_t _arc_len = (s).len; \
	msRefPayload* _arc_sp = (s).p; \
	msRefPayload* _arc_newp = NULL; \
	if (_arc_sp) { \
		size_t _arc_sz = sizeof(msRefPayload) + (size_t)_arc_sp->cap * sizeof(void*); \
		_arc_newp = (msRefPayload*)calloc(1, _arc_sz); \
		_arc_newp->cap = _arc_sp->cap; \
		for (int64_t _arc_i = 0; _arc_i < _arc_len; _arc_i++) { \
			_arc_newp->data[_arc_i] = _arc_sp->data[_arc_i]; \
			if (_arc_newp->data[_arc_i]) msIncRef(_arc_newp->data[_arc_i]); \
		} \
	} \
	msRefArrayDestroy(&(d)); \
	(d).len = _arc_len; \
	(d).p = _arc_newp; \
} while(0)
#define msArrayRefTrace(arr, cb)       do { \
	for (int64_t _art_i = 0; _art_i < (arr).len && (arr).p; _art_i++) { \
		if ((arr).p->data[_art_i]) ((void(*)(void*))(cb))((arr).p->data[_art_i]); \
	} \
} while(0)
#define msArrayRefWasMoved(arr)        msArrayWasMoved(arr)
#define msArrayUint8Destroy(arr)       msUint8ArrayDestroy(&(arr))
#define msArrayUint8WasMoved(arr)      msArrayWasMoved(arr)
#define msArrayUint8Sink(d, s)         do { msArrayDestroy(d); (d) = (s); } while(0)

/* --- Ref/Ptr lifecycle (generic heap objects) --- */
#define msIncref(p)           msIncRef(p)
#define msDecref(p)           do { \
	if ((p) != NULL && msDecRefIsLast(p)) { \
		const msTypeInfo* __t = msHeader(p)->type; \
		if (__t != NULL && __t->destroyFn != NULL) __t->destroyFn(p); \
		msDestroyAndDispose(p); \
	} \
} while(0)
#define msPtrWasMoved(p)      msWasMoved(p)

/* --- ORC-aware ref lifecycle for cyclic types (Standard reference implementation parity) --- */
#ifdef MS_ORC
#define msIncrefCyclic(p)     do { if ((p) != NULL) msOrcIncRef(p); } while(0)
#define msDecrefCyclic(p)     do { \
	if ((p) != NULL && msOrcDecRefIsLast(p)) { \
		const msTypeInfo* __t = msHeader(p)->type; \
		if (__t != NULL && __t->destroyFn != NULL) __t->destroyFn(p); \
		msDestroyAndDispose(p); \
	} \
} while(0)
#else
#define msIncrefCyclic(p)     msIncref(p)
#define msDecrefCyclic(p)     msDecref(p)
#endif

/* --- Closure lifecycle --- */
#define msClosureDestroy(c)   do { if ((c).env != NULL) { msDecref((c).env); } (c).fn = NULL; (c).env = NULL; } while(0)
#define msClosureCopy(c)      do { if ((c).env != NULL) msIncRef((c).env); } while(0)
#define msClosureWasMoved(c)  do { (c).fn = NULL; (c).env = NULL; } while(0)
#define msClosureSink(d, s)   do { msClosureDestroy(d); (d) = (s); } while(0)
#define msClosureTrace(c, _env) do { if ((c).env != NULL) msOrcTraceRef((c).env, (_env)); } while(0)

/* --- Map lifecycle --- */
/* DRC emits these as fn(varName) — macros handle address-of */
#define msMapFree(m)          msMapDestroy(&(m))
#define msMapCopy(m)          do { msMap __mc = msMapCopyFn(m); (m) = __mc; } while(0)
#define msMapWasMoved(m)      do { (m).len = 0; (m).p = NULL; } while(0)
#define msMapSink(d, s)       do { msMapDestroy(&(d)); (d) = (s); } while(0)
#define msMapTrace(m)         /* TODO: ORC trace */

/* --- Set = Map with NULL values --- */
typedef msMap msSet;
#define msSetNew()            msMapNew(NULL)
#define msSetFree(s)          msMapFree(s)
#define msSetCopy(s)          msMapCopy(s)
#define msSetWasMoved(s)      msMapWasMoved(s)
#define msSetSink(d, s)       msMapSink(d, s)
#define msSetTrace(s)         msMapTrace(s)

/* --- Named object wasMoved (no-op for value-type named objects) --- */
#define msObjectWasMoved(p)   /* no-op */

/* Thread runtime (msSpawn — needs msIncRef/msDecref/msException above) */
#include "std/core/promise/thread.h"

/* AbortController / AbortSignal (needs msString + msThrow above) */
#include "abort.h"

/* Promise combinators (Promise.all, Promise.race) */
#include "std/core/promise/combinator.h"

/* String boxing for spawn — msString must be defined before this */
static inline void* msBoxString(msString v) {
	msString* p = (msString*)malloc(sizeof(msString));
	*p = v;
	if (v.p) msIncRef(v.p);
	return p;
}
static inline msString msUnboxString(void* p) {
	msString v = *(msString*)p;
	free(p);
	return v;
}

/* ===== Error Reporting ===== */

/* Bounds check failure — prints error and exits */
_Noreturn void msRaiseIndexError(int64_t idx, int64_t len);

/* ===== Bounds-Checked Array Access ===== */
/* GCC statement expression returning lvalue via dereferenced-pointer trick.
   Works with any MS_ARRAY(T) typedef. Supports both reads and writes. */

#define msArrayAccess(a, i) (*({ \
	int32_t __idx = (i); \
	if ((uint32_t)__idx >= (uint32_t)(a).len) msRaiseIndexError(__idx, (a).len); \
	&((a).p->data[__idx]); \
}))

/* Aliases for backward compatibility — all identical to msArrayAccess */
#define msNumberArrayAccess msArrayAccess
#define msStringArrayAccess msArrayAccess
#define msRefArrayAccess    msArrayAccess
#define msUint8ArrayAccess  msArrayAccess

#define msSizedArrayAccess(a, i, n) (*({ \
	int32_t __idx = (i); \
	if ((uint32_t)__idx >= (uint32_t)(n)) msRaiseIndexError(__idx, (n)); \
	&((a).data[__idx]); \
}))

#define msSpanAccess(a, i) (*({ \
	int32_t __idx = (i); \
	if ((uint32_t)__idx >= (uint32_t)(a).len) msRaiseIndexError(__idx, (a).len); \
	&((a).data[__idx]); \
}))

/* String char access — TypeScript s[i] parity (character-indexed) */
#define msStringCharAccess(s, i) msStringCharAt((s), (i))

/* ===== Range-Checked Integer Casts ===== */
/* Parity: standard reference range checks and code generation patterns.
   Inline condition (fast path), helper call only on error (slow path). */

_Noreturn void msRaiseRangeError(int64_t val, int64_t lo, int64_t hi);

static inline int8_t msCheckRangeI8(double v, int64_t lo, int64_t hi) {
	int64_t iv = (int64_t)v;
	if (iv < lo || iv > hi) msRaiseRangeError(iv, lo, hi);
	return (int8_t)iv;
}

static inline uint8_t msCheckRangeU8(double v, int64_t lo, int64_t hi) {
	int64_t iv = (int64_t)v;
	if (iv < lo || iv > hi) msRaiseRangeError(iv, lo, hi);
	return (uint8_t)iv;
}

static inline int16_t msCheckRangeI16(double v, int64_t lo, int64_t hi) {
	int64_t iv = (int64_t)v;
	if (iv < lo || iv > hi) msRaiseRangeError(iv, lo, hi);
	return (int16_t)iv;
}

static inline uint16_t msCheckRangeU16(double v, int64_t lo, int64_t hi) {
	int64_t iv = (int64_t)v;
	if (iv < lo || iv > hi) msRaiseRangeError(iv, lo, hi);
	return (uint16_t)iv;
}

static inline int32_t msCheckRangeI32(double v, int64_t lo, int64_t hi) {
	int64_t iv = (int64_t)v;
	if (iv < lo || iv > hi) msRaiseRangeError(iv, lo, hi);
	return (int32_t)iv;
}

static inline uint32_t msCheckRangeU32(double v, int64_t lo, int64_t hi) {
	int64_t iv = (int64_t)v;
	if (iv < lo || iv > hi) msRaiseRangeError(iv, lo, hi);
	return (uint32_t)iv;
}

#endif /* SYSTEM_H */
