/*
 * MetaScript System Header — Master Include
 * This is the single header that generated C code includes.
 * It pulls in ARC, String, and Array runtimes.
 */
#ifndef SYSTEM_H
#define SYSTEM_H

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* DRC foundation (refcount + ORC cycle collector) */
#include "runtime/drc.h"

/* String runtime (msString, all string ops) */
#include "runtime/core/string.h"

/* Array runtime (msNumberArray, msStringArray, msRefArray) */
#include "runtime/core/array.h"

/* Buffer runtime (msBuffer — binary data, byte-oriented) */
#include "runtime/core/buffer.h"

/* ===== Type Aliases (C89 portability + codegen convenience) ===== */
typedef bool MS_BOOL;
#define MS_TRUE true
#define MS_FALSE false
#define MS_NIL NULL

/* ===== I/O ===== */

void msPrintln(msString s);

/* ===== DRC Lifecycle Stubs ===== */

/* Error flag — declared later (after MS_THREAD_LOCAL is defined by future.h) */

/* Closure function pointer types — with env (for lifted closures) */
typedef void (*msClosureFn)(void*, ...);
typedef double (*msClosureFnD)(void*, ...);
typedef MS_BOOL (*msClosureFnB)(void*, ...);
typedef msString (*msClosureFnS)(void*, ...);
typedef int32_t (*msClosureFnI)(void*, ...);
typedef int64_t (*msClosureFnI64)(void*, ...);
typedef void* (*msClosureFnP)(void*, ...);
/* Direct function pointer casts for named functions wrapped as closures:
   Standard reference pattern — per-call-site typed casts generated by closureCallLower.
   No generic typedefs needed; each call site gets its own typed cast like:
     ((MS_BOOL(*)(double))(pred.fn))(args)
   This avoids -Wdeprecated-non-prototype warnings from empty-paren typedefs. */
#ifndef MS_CLOSURE_DEFINED
#define MS_CLOSURE_DEFINED
typedef struct {
	msClosureFn fn;
	void* env;
} msClosure;
#endif

/* Closure array: msClosure structs stored INLINE (16B stride). Single
 * typed helper works for ALL closure types — closure layout is uniform
 * (per-env-type cleanup is virtual-dispatched via env's typeInfo, not
 * per-closure-type variation). */
#ifndef MS_CLOSURE_ARRAY_DEFINED
#define MS_CLOSURE_ARRAY_DEFINED
typedef struct {
	int64_t cap;
	msClosure data[];
} msClosurePayload;

typedef struct {
	int64_t len;
	msClosurePayload* p;
} msClosureArray;

#define MS_EMPTY_CLOSURE_ARRAY ((msClosureArray){0, NULL})

void msClosureArrayDestroy(msClosureArray* arr);
void msClosureArrayPush(msClosureArray* arr, msClosure value);
void msClosureArrayCopy(msClosureArray* dest, const msClosureArray* src);
void msClosureArrayWasMoved(msClosureArray* arr);
#endif

/* Exception handling — declared before future.h so a failed-future read can
 * surface the caught exception object on msCurrException (await re-raise). */
typedef struct {
	const char* message;
	int code;
} msException;

/* Heap Error object — DRC-managed. Layout MUST match the std `Error` class
 * struct (single msString message) so a caught `Error*` reads it directly. */
typedef struct {
	msString message;
} msError;

extern const msTypeInfo msErrorTypeInfo;
msError* msMakeError(msString message);

/* Async future runtime (msFuture, msFutureCreate/Complete/etc.) */
#include "runtime/promise/future.h"

/* Async dispatcher (event loop, msWaitFor, sleepAsync) */
#include "runtime/promise/dispatch.h"

/* MS_THREAD_LOCAL becomes available via future.h above. */
extern MS_THREAD_LOCAL bool msErr;
extern MS_THREAD_LOCAL msException* msCurrException;
void msClearException(void);
void msDiscardCurrentException(void);
void msThrow(msString msg);

/* Check-and-clear the pending-exception flag. Emitted by the `try await X catch Y`
 * lowering immediately after the await read (which sets msErr on a rejected
 * future) to route to the catch value. */
static inline bool msErrTake(void) {
	if (msErr) { msErr = false; msClearException(); return true; }
	return false;
}

/* ===== DRC Lifecycle Macros ===== */
/* DRC passes args by value — macros access the variable directly for mutation. */

/* --- String lifecycle --- */
#define msStringDecref(s)     msStringDestroy(s)
#define msStringIncref(s)     do { \
	if ((s).p != NULL && !msIsLiteral(s)) { \
		msString __c = msStringNew((s).p->data, (s).len); \
		(s) = __c; \
	} \
} while(0)
/* =copy(var dest, src) — string copy-on-write assignment.
   Literal CoW: shallow copy for literals (pointer only, no alloc).
   Buffer reuse: if dest has enough capacity, memcpy without malloc.
   Full copy only when dest buffer is too small or is a literal. */
static inline void msStringCopy(msString* dest, msString src) {
	/* Identity: same pointer + same length = same string */
	if (dest->p == src.p && dest->len == src.len) return;
	/* Shared payload (e.g. after bitwise copy): both point to same buffer.
	   Don't free — source still owns it. Must allocate a fresh independent copy. */
	if (dest->p == src.p) {
		if (src.p != NULL && !msIsLiteral(src)) {
			*dest = msStringNew(src.p->data, src.len);
		} else {
			dest->len = src.len;  /* literal: just update length */
		}
		return;
	}
	/* Source is literal (or interned char): shallow copy — pointer only */
	if (msIsLiteral(src)) {
		if (!msIsLiteral(*dest)) free(dest->p);
		dest->len = src.len;
		dest->p = src.p;
		return;
	}
	/* Source is heap: try buffer reuse (reuse if capacity sufficient) */
	if (!msIsLiteral(*dest) && dest->p != NULL &&
		(dest->p->cap & MS_CAP_MASK) >= src.len) {
		dest->len = src.len;
		memcpy(dest->p->data, src.p->data, src.len + 1);
		return;
	}
	/* Must allocate new buffer */
	msString newStr = msStringNew(src.p->data, src.len);
	if (!msIsLiteral(*dest)) free(dest->p);
	*dest = newStr;
}
#define msStringWasMoved(s)   do { (s).len = 0; (s).p = NULL; } while(0)
#define msStringSink(d, s)    do { msStringDestroy(d); (d) = (s); } while(0)

/* --- Array lifecycle (unified) — uniquely owned payloads --- */
/* Reference parity: payloads are never shared. DRC emits deep copy or move. */
#define msArrayDestroy(arr)            do { if ((arr).p) { free((arr).p); } (arr).p = NULL; (arr).len = 0; } while(0)
#define msArrayWasMoved(arr)           do { (arr).len = 0; (arr).p = NULL; } while(0)
/* msArrayCopy: 1-arg = in-place deep copy (detach from shared payload), 2-arg = deep copy into different dest.
 * Reference parity: =copy for seq always allocates a fresh payload (unique ownership). */
#define msArrayCopy1(arr) do { \
	if ((arr).p != NULL) { \
		size_t _ac1_esz = sizeof((arr).p->data[0]); \
		size_t _ac1_sz = sizeof(msArrayPayloadBase) + (size_t)(arr).p->cap * _ac1_esz; \
		__typeof__((arr).p) _ac1_newp = (__typeof__((arr).p))malloc(_ac1_sz); \
		_ac1_newp->cap = (arr).p->cap; \
		memcpy(_ac1_newp->data, (arr).p->data, (size_t)(arr).len * _ac1_esz); \
		(arr).p = _ac1_newp; \
	} \
} while(0)
#define msArrayCopy2(d, s)             do { \
	if ((s).p != NULL) { \
		size_t _ac_esz = sizeof((s).p->data[0]); \
		size_t _ac_sz = sizeof(msArrayPayloadBase) + (size_t)(s).p->cap * _ac_esz; \
		(d).p = (__typeof__((s).p))malloc(_ac_sz); \
		(d).p->cap = (s).p->cap; \
		memcpy((d).p->data, (s).p->data, (size_t)(s).len * _ac_esz); \
	} else { \
		(d).p = NULL; \
	} \
	(d).len = (s).len; \
} while(0)
#define msArrayCopy_GET(_1, _2, NAME, ...) NAME
#define msArrayCopy(...) msArrayCopy_GET(__VA_ARGS__, msArrayCopy2, msArrayCopy1)(__VA_ARGS__)
#define msArraySetLen(d, s)            msArraySetLenGeneric(&(d), (s).len, sizeof((s).p->data[0]))

/* --- Legacy aliases (used by classify.ms for DRC injection layer) --- */
#define msArrayNumberWasMoved(arr)     msArrayWasMoved(arr)
#define msArrayNumberSink(d, s)        do { msArrayDestroy(d); (d) = (s); } while(0)
#define msArrayStringDestroy(arr)      msStringArrayDestroy(&(arr))
/* Deep copy: allocate new payload, copy each string element.
 * Cache (s) in a local to prevent double-evaluation when `s` is a call. */
#define msArrayStringCopy(d, s)        do { \
	msStringArray _asc_src = (s); \
	int64_t _asc_len = _asc_src.len; \
	msStringPayload* _asc_sp = _asc_src.p; \
	msStringPayload* _asc_newp = NULL; \
	if (_asc_sp) { \
		size_t _asc_sz = sizeof(msStringPayload) + (size_t)_asc_sp->cap * sizeof(msString); \
		_asc_newp = (msStringPayload*)calloc(1, _asc_sz); \
		_asc_newp->cap = _asc_sp->cap; \
		for (int64_t _asc_i = 0; _asc_i < _asc_len; _asc_i++) { \
			_asc_newp->data[_asc_i] = _asc_sp->data[_asc_i]; \
			msStringIncref(_asc_newp->data[_asc_i]); \
		} \
	} \
	msStringArrayDestroy(&(d)); \
	(d).len = _asc_len; \
	(d).p = _asc_newp; \
} while(0)
#define msArrayStringWasMoved(arr)     msArrayWasMoved(arr)
#define msArrayStringSink(d, s)        do { msArrayDestroy(d); (d) = (s); } while(0)
#define msArrayRefDestroy(arr)         msRefArrayDestroy((msRefArray*)&(arr))
/* Deep copy: allocate new payload, copy each ref element with incref.
 * Cache (s) in a local to prevent double-evaluation when `s` is a call. */
#define msArrayRefCopy(d, s)           do { \
	msRefArray _arc_src = (s); \
	int64_t _arc_len = _arc_src.len; \
	msRefPayload* _arc_sp = (msRefPayload*)_arc_src.p; \
	msRefPayload* _arc_newp = NULL; \
	if (_arc_sp) { \
		size_t _arc_sz = sizeof(msRefPayload) + (size_t)_arc_sp->cap * sizeof(void*); \
		_arc_newp = (msRefPayload*)calloc(1, _arc_sz); \
		_arc_newp->cap = _arc_sp->cap; \
		for (int64_t _arc_i = 0; _arc_i < _arc_len; _arc_i++) { \
			_arc_newp->data[_arc_i] = _arc_sp->data[_arc_i]; \
			if (_arc_newp->data[_arc_i]) msIncRef(_arc_newp->data[_arc_i]); \
		} \
	} \
	msRefArrayDestroy((msRefArray*)&(d)); \
	(d).len = _arc_len; \
	(d).p = (void*)_arc_newp; \
} while(0)
/* Sink semantics: old dest payload freed (elements NOT decref'd — ownership
 * transfers from source which already holds the only refs). */
#define msArrayRefSink(d, s)           do { \
	msRefArray _ars_src = (s); \
	if ((d).p != NULL) { free((msRefPayload*)(d).p); } \
	(d) = _ars_src; \
} while(0)
#define msArrayRefTrace(arr, cb)       do { \
	for (int64_t _art_i = 0; _art_i < (arr).len && (arr).p; _art_i++) { \
		if ((arr).p->data[_art_i]) msOrcTraceRef(&(arr).p->data[_art_i], (cb)); \
	} \
} while(0)
#define msArrayRefWasMoved(arr)        msArrayWasMoved(arr)
#define msArrayUint8Destroy(arr)       msUint8ArrayDestroy(&(arr))
#define msArrayUint8WasMoved(arr)      msArrayWasMoved(arr)
#define msArrayUint8Sink(d, s)         do { msArrayDestroy(d); (d) = (s); } while(0)

/* Closure array: per-element destroy decrefs env, leaves fn (untracked
 * function pointer) alone. Single helper for ALL closure types — closure
 * value layout is uniform. */
#define msArrayClosureDestroy(arr)     msClosureArrayDestroy(&(arr))
#define msArrayClosureCopy(d, s)       msClosureArrayCopy(&(d), &(s))
#define msArrayClosureSink(d, s)       do { msClosureArrayDestroy(&(d)); (d) = (s); } while(0)
#define msArrayClosureWasMoved(arr)    msArrayWasMoved(arr)

/* --- Ref/Ptr lifecycle (generic heap objects) --- */
#define msIncref(p)           msIncRef(p)
#define msDecref(p)           do { \
	if ((p) != NULL) { \
		const msTypeInfo* __t = msHeader(p)->type; \
		if (__t != NULL && (__t->flags & MS_TYPE_FLAG_FUTURE)) { \
			msFutureDeferredRelease(p); \
		} else if (msDecRefIsLast(p)) { \
			MS_DESTROY_DISPATCH(__t, p); \
			msDestroyAndDispose(p); \
		} \
	} \
} while(0)
#define msPtrWasMoved(p)      msWasMoved(p)

/* --- Arc<T> atomic ref lifecycle (cross-thread shared; decref tail == msDecref) --- */
#define msAtomicIncref(p)     msAtomicIncRef(p)
#define msAtomicDecref(p)     do { \
	if ((p) != NULL && msAtomicDecRefIsLast(p)) { \
		const msTypeInfo* __t = msHeader(p)->type; \
		MS_DESTROY_DISPATCH(__t, p); \
		msDestroyAndDispose(p); \
	} \
} while(0)

/* --- ORC-aware ref lifecycle for cyclic types --- */
#ifdef MSGC_ORC
#define msIncrefCyclic(p)     do { if ((p) != NULL) msOrcIncRef(p); } while(0)
#define msDecrefCyclic(p)     do { \
	if ((p) != NULL) { \
		const msTypeInfo* __t = msHeader(p)->type; \
		if (__t != NULL && (__t->flags & MS_TYPE_FLAG_FUTURE)) { \
			msFutureDeferredRelease(p); \
		} else if (msOrcDecRefIsLast(p)) { \
			MS_DESTROY_DISPATCH(__t, p); \
			msDestroyAndDispose(p); \
		} \
	} \
} while(0)
#else
#define msIncrefCyclic(p)     msIncref(p)
#define msDecrefCyclic(p)     msDecref(p)
#endif

/* --- Cyclic ref =copy: incref new, assign, decref old AFTER assign (Nim attachedAsgn
 * isCyclic order — old's destroy may collect; dest must already hold the new value) --- */
#define msRefCopyCyclic(d, s) do { \
	void* __rcold = (void*)(d); \
	msIncrefCyclic(s); \
	(d) = (s); \
	msDecrefCyclic(__rcold); \
} while(0)

/* --- Closure lifecycle --- */
#define msClosureDestroy(c)   do { if ((c).env != NULL) { msDecref((c).env); } (c).fn = NULL; (c).env = NULL; } while(0)
#define msClosureCopy(c)      do { if ((c).env != NULL) msIncRef((c).env); } while(0)
#define msClosureWasMoved(c)  do { (c).fn = NULL; (c).env = NULL; } while(0)
#define msClosureSink(d, s)   do { msClosureDestroy(d); (d) = (s); } while(0)
#define msClosureTrace(c, _env) do { if ((c).env != NULL) msOrcTraceRef(&(c).env, (_env)); } while(0)

/* --- Map lifecycle --- */
/* DRC emits these as fn(varName) — macros handle address-of */
#define msMapFree(m)          msMapDestroy(&(m))
#define msMapCopy(m)          do { msMap __mc = msMapCopyFn(m); (m) = __mc; } while(0)
#define msMapWasMoved(m)      do { (m).len = 0; (m).p = NULL; } while(0)
#define msMapSink(d, s)       do { msMapDestroy(&(d)); (d) = (s); } while(0)
#define msMapTrace(m)         /* TODO: ORC trace */

/* --- Named object wasMoved (no-op for value-type named objects) --- */
#define msObjectWasMoved(p)   /* no-op */

/* AwaitGroup — structured fan-out primitive (PARALOCK Phase 2). Must precede
 * thread.h because msSpawnCtx carries an optional msAwaitGroup* completion target. */
#include "runtime/promise/awaitGroup.h"

/* Thread runtime (msSpawn — needs msIncRef/msDecref/msException above) */
#include "runtime/promise/thread.h"

/* AbortController / AbortSignal (needs msString + msThrow above) */
#include "runtime/core/abort.h"

/* Promise combinators (Promise.all, Promise.race) */
#include "runtime/promise/combinator.h"

/* String boxing for spawn/Promise — msString must be defined before this.
 * Reference parity: check strlitFlag before refcounting.
 * String literals have MS_STRLIT_FLAG in cap and NO heap header — msIncRef
 * on a literal would write into adjacent static memory (corruption). */
static inline void* msBoxString(msString v) {
	msString* p = (msString*)malloc(sizeof(msString));
	*p = v;
	if (v.p && !(v.p->cap & MS_STRLIT_FLAG)) {
		msIncRef(v.p);  /* heap string — incref to keep payload alive */
	}
	return p;
}
static inline msString msUnboxString(void* p) {
	msString v = *(msString*)p;
	free(p);  /* free the box shell; string payload survives via its own refcount */
	return v;
}

/* msFuture_msString — defined here (after msString type is available from string/native.h) */
#ifndef msFuture_msString_DEFINED
#define msFuture_msString_DEFINED
MS_FUTURE_STRUCT(msFuture_msString, msString);
MS_DEFINE_FUTURE_CHAIN(msFutureChain_msString, msFuture_msString)
MS_DEFINE_FUTURE_THEN(msFutureThen_msString, msFuture_msString, msString, msString)
MS_DEFINE_FUTURE_FINALLY(msFutureFinally_msString, msFuture_msString)

/* Typed .catch — error handler always receives msString.
 * Success path propagates typed value via msFutureCompleteT. */
MS_DEFINE_FUTURE_CATCH(msFutureCatch_double,   msFuture_double)
MS_DEFINE_FUTURE_CATCH(msFutureCatch_int32,    msFuture_int32)
MS_DEFINE_FUTURE_CATCH(msFutureCatch_int64,    msFuture_int64)
MS_DEFINE_FUTURE_CATCH(msFutureCatch_bool,     msFuture_bool)
MS_DEFINE_FUTURE_CATCH(msFutureCatch_ptr,      msFuture_ptr)
MS_DEFINE_FUTURE_CATCH(msFutureCatch_msString, msFuture_msString)

/* Per-T Promise.all — msString variant. Input values are msString structs (16B inline);
 * output is msStringArray holding msString slots populated via msStringCopy
 * (ownership-correct — increments underlying string refcount). */
#define MS_COPY_STRING(dst, src) msStringCopy((dst), *(src))
MS_PROMISE_ALL_FOR(msString, msFuture_msString, msString, msStringArray, msStringPayload, MS_COPY_STRING)
#endif

/* Per-type read for msString. All futures now store values inline. */
static inline msString msFutureReadString(void* fp) {
	msFutureBase* f = (msFutureBase*)fp;
	assert(atomic_load_explicit(&f->finished, memory_order_acquire) && "Future not yet finished");
	if (f->cancelled || f->failed) { msFutureRaiseFrom(f); return MS_EMPTY_STRING; }
	return ((msFuture_msString*)fp)->value;
}

/* Generic struct boxing for spawn — any value type via memcpy.
 * Used when spawn closure returns a struct (Result, interface, etc.).
 * Caller passes &value and sizeof(Type). Box allocates heap copy.
 * Unbox: cast void* to Type*, dereference, free. */
static inline void* msBoxStruct(const void* val, size_t size) {
	void* p = malloc(size);
	if (p) memcpy(p, val, size);
	return p;
}

/* ===== Error Reporting ===== */

/* Bounds check failure — prints error and exits */
_Noreturn void msRaiseIndexError(int64_t idx, int64_t len);

/* Concurrent Map/Set access detected — unrecoverable (Go fatal model: a detected
   race means memory may already be corrupt, so unwinding past it is unsafe). */
_Noreturn void msMapFatal(msString msg);

/* Reference-identity hash for Map<unknown, _> keys (JS Map / Java Object.hashCode parity).
   XOR-folds the 64-bit address to 32 bits, then applies Knuth multiplicative hash
   to match hashNumber's distribution. Map's `key === key` equality provides the
   matching pointer comparison. */
static inline int64_t msPtrHash(const void* p) {
	uint64_t a = (uint64_t)(uintptr_t)p;
	uint32_t folded = (uint32_t)((a >> 32) ^ (a & 0xFFFFFFFFULL));
	if (folded == 0) return 314159265;
	int64_t h = (int64_t)folded * (int64_t)2654435761LL;
	h &= 0xFFFFFFFFLL;
	if (h == 0) return 314159265;
	return h;
}

/* ===== Bounds-Checked Array Access ===== */
/* GCC statement expression returning lvalue via dereferenced-pointer trick.
   Works with any MS_ARRAY(T) typedef. Supports both reads and writes. */

#define msArrayAccess(a, i) (*({ \
	int32_t __idx = (i); \
	if ((uint32_t)__idx >= (uint32_t)(a).len) msRaiseIndexError(__idx, (a).len); \
	&((a).p->data[__idx]); \
}))

/* Aliases for backward compatibility — all identical to msArrayAccess */
#define msNumberArrayAccess msArrayAccess
#define msStringArrayAccess msArrayAccess
#define msRefArrayAccess    msArrayAccess
#define msUint8ArrayAccess  msArrayAccess

#define msSizedArrayAccess(a, i, n) (*({ \
	int32_t __idx = (i); \
	if ((uint32_t)__idx >= (uint32_t)(n)) msRaiseIndexError(__idx, (n)); \
	&((a).data[__idx]); \
}))

#define msSpanAccess(a, i) (*({ \
	int32_t __idx = (i); \
	if ((uint32_t)__idx >= (uint32_t)(a).len) msRaiseIndexError(__idx, (a).len); \
	&((a).data[__idx]); \
}))

/* String char access — TypeScript s[i] parity (character-indexed) */
#define msStringCharAccess(s, i) msStringCharAt((s), (i))

/* ===== Range-Checked Integer Casts ===== */
/* Parity: standard reference range checks and code generation patterns.
   Inline condition (fast path), helper call only on error (slow path). */

_Noreturn void msRaiseRangeError(int64_t val, int64_t lo, int64_t hi);

static inline int8_t msCheckRangeI8(double v, int64_t lo, int64_t hi) {
	int64_t iv = (int64_t)v;
	if (iv < lo || iv > hi) msRaiseRangeError(iv, lo, hi);
	return (int8_t)iv;
}

static inline uint8_t msCheckRangeU8(double v, int64_t lo, int64_t hi) {
	int64_t iv = (int64_t)v;
	if (iv < lo || iv > hi) msRaiseRangeError(iv, lo, hi);
	return (uint8_t)iv;
}

static inline int16_t msCheckRangeI16(double v, int64_t lo, int64_t hi) {
	int64_t iv = (int64_t)v;
	if (iv < lo || iv > hi) msRaiseRangeError(iv, lo, hi);
	return (int16_t)iv;
}

static inline uint16_t msCheckRangeU16(double v, int64_t lo, int64_t hi) {
	int64_t iv = (int64_t)v;
	if (iv < lo || iv > hi) msRaiseRangeError(iv, lo, hi);
	return (uint16_t)iv;
}

static inline int32_t msCheckRangeI32(double v, int64_t lo, int64_t hi) {
	int64_t iv = (int64_t)v;
	if (iv < lo || iv > hi) msRaiseRangeError(iv, lo, hi);
	return (int32_t)iv;
}

static inline uint32_t msCheckRangeU32(double v, int64_t lo, int64_t hi) {
	int64_t iv = (int64_t)v;
	if (iv < lo || iv > hi) msRaiseRangeError(iv, lo, hi);
	return (uint32_t)iv;
}

#endif /* SYSTEM_H */
